#!/bin/bash

echo "Starting Panama FFM API bindings generation ..."
REPODIR=$(cd $(dirname $0); cd ../../ ; pwd)
CURDIR=$(cd $(dirname $0); pwd)
CUDA_HOME=$(which nvcc | cut -d/ -f-4)
OUTPUT_FOLDER="${CURDIR}/bindings"
TARGET_PACKAGE="com.nvidia.cuvs.internal.panama"
GENERATED_PANAMA_BINDINGS_PATH="${OUTPUT_FOLDER}/${TARGET_PACKAGE//./\/}"
PANAMA_JAVA_FILES_PATH="${REPODIR}/java/cuvs-java/src/main/java22/${TARGET_PACKAGE//./\/}"

# Use Jextract utility to generate panama bindings
jextract \
 --include-dir ${REPODIR}/cpp/build/_deps/dlpack-src/include/ \
 --include-dir ${CUDA_HOME}/include \
 --include-dir ${REPODIR}/cpp/include \
 --output ${OUTPUT_FOLDER} \
 --target-package ${TARGET_PACKAGE} \
 --header-class-name PanamaFFMAPI \
 ${CURDIR}/headers.h

# Did Jextract complete normally? If not, stop and return
JEXTRACT_RETURN_VALUE=$?
if [ $JEXTRACT_RETURN_VALUE == 0 ]
then
  echo "Jextract SUCCESS"
else
  echo "Jextract encountered issues (returned value ${JEXTRACT_RETURN_VALUE})"
  exit $JEXTRACT_RETURN_VALUE
fi

# Insert license headers in the generated files
for BINDING_FILE in ${GENERATED_PANAMA_BINDINGS_PATH}/*; do
  sed -i '1s/^/\n\/\/ NOTE: PLEASE DO NOT EDIT THIS FILE MANUALLY\n/' $BINDING_FILE
  cat ${CURDIR}/license-header.txt $BINDING_FILE > temp && mv temp $BINDING_FILE
done

# Add the panama binding classes in the panama java folder
for GENERATED_PANAMA_JAVA_FILE in ${GENERATED_PANAMA_BINDINGS_PATH}/*; do
  mv $GENERATED_PANAMA_JAVA_FILE $PANAMA_JAVA_FILES_PATH
done

# Cleanup
if test -d $OUTPUT_FOLDER; then
  rm -rf $OUTPUT_FOLDER
fi

echo "Panama FFM API bindings generation done"
