#!/bin/bash

REPODIR=$(cd $(dirname $0); cd ../../ ; pwd)
CURDIR=$(cd $(dirname $0); pwd)
CUDA_HOME=$(which nvcc | cut -d/ -f-4)
OUTPUT_FOLDER="${CURDIR}/bindings"
TARGET_PACKAGE="com.nvidia.cuvs.internal.panama"
TARGET_PACKAGE_PATH="${OUTPUT_FOLDER}/${TARGET_PACKAGE//./\/}"

jextract \
 --include-dir ${REPODIR}/cpp/build/_deps/dlpack-src/include/ \
 --include-dir ${CUDA_HOME}/include \
 --include-dir ${REPODIR}/cpp/include \
 --output ${OUTPUT_FOLDER} \
 --target-package ${TARGET_PACKAGE} \
 --header-class-name PanamaBindings \
 ${CURDIR}/headers.h

# Insert license headers in the generated files
for file in ${TARGET_PACKAGE_PATH}/*; do
  sed -i '1s/^/\n\/\/ NOTE: PLEASE DO NOT EDIT THIS FILE MANUALLY\n/' $file
  cat ${CURDIR}/license-header.txt $file > temp && mv temp $file
done
