name: cuvs_cagra_diskann
constraints:
  build: cuvs_bench.config.algos.constraints.cuvs_cagra_build
groups:
  base:
    build:
      graph_degree: [32, 64, 96]
      intermediate_graph_degree: [32, 64, 128]
      graph_build_algo: ["NN_DESCENT"]
    search:
      L_search: [10, 20, 30, 40, 50, 100, 200, 300]
