name: faiss_gpu_ivf_pq
constraints:
  build: cuvs_bench.config.algos.constraints.faiss_gpu_ivf_pq_build
  search: cuvs_bench.config.algos.constraints.faiss_gpu_ivf_pq_search
groups:
  base:
    build:
      nlist: [1024, 2048, 4096]
      M: [96, 64]
      ratio: [10]
      usePrecomputed: [False, True]
      useFloat16: [True]
      use_cuvs: [False]
      bitsPerCode: [8]
    search:
      nprobe: [10, 20, 30, 40, 50, 100, 200]
      refine_ratio: [4, 8, 16]
  cuvs:
    build:
      nlist: [1024, 2048, 4096]
      M: [384, 192]
      ratio: [10]
      useFloat16: [False]
      use_cuvs: [True]
      bitsPerCode: [8, 6, 5, 4]
    search:
      nprobe: [10, 20, 30, 40, 50, 100, 200]
      refine_ratio: [2, 4, 8]
