name: faiss_gpu_ivf_pq
constraints:
  build: cuvs_bench.config.algos.constraints.faiss_gpu_ivf_pq_build
  search: cuvs_bench.config.algos.constraints.faiss_gpu_ivf_pq_search
groups:
  base:
    build:
      nlist: [1024, 2048, 4096, 8192]
      M: [64, 96]
      ratio: [4]
      usePrecomputed: [False, True]
      useFloat16: [False, True]
      use_cuvs: [False]
      bitsPerCode: [8]
    search:
      nprobe: [10, 50, 100, 200]
      refine_ratio: [1, 2, 4]
  basecuvs:
    build:
      nlist: [1024, 2048, 4096, 8192]
      M: [96, 192, 384]
      ratio: [4]
      usePrecomputed: [False]
      useFloat16: [False, True]
      use_cuvs: [True]
      bitsPerCode: [8]
    search:
      nprobe: [10, 50, 100, 200]
      refine_ratio: [1, 2, 4]
  large:
    build:
      nlist: [16384, 32768, 65536]
      M: [64, 96]
      ratio: [4]
      usePrecomputed: [False, True]
      useFloat16: [True]
      use_cuvs: [False]
      bitsPerCode: [8]
    search:
      nprobe: [20, 30, 40, 50, 100, 200, 500, 1000]
      refine_ratio: [1, 2, 4]
  largecuvs:
    build:
      nlist: [16384, 32768, 65536]
      M: [96, 192, 384]
      ratio: [4]
      usePrecomputed: [False]
      useFloat16: [False, True]
      use_cuvs: [True]
      bitsPerCode: [8, 6, 5, 4]
    search:
      nprobe: [20, 30, 40, 50, 100, 200, 500, 1000]
      refine_ratio: [1, 2, 4]
  100M:
    build:
      nlist: [100000]
      M: [64, 96]
      ratio: [4]
      usePrecomputed: [False, True]
      useFloat16: [True]
      use_cuvs: [False]
      bitsPerCode: [8]
    search:
      nprobe: [20, 30, 40, 50, 100, 200, 500, 1000]
      refine_ratio: [1]
  100Mcuvs:
    build:
      nlist: [100000]
      M: [192, 384]
      ratio: [4]
      useFloat16: [False, True]
      use_cuvs: [True]
      bitsPerCode: [8, 6, 5, 4]
    search:
      nprobe: [20, 30, 40, 50, 100, 200, 500, 1000]
      refine_ratio: [1]
