name: faiss_gpu_cagra
constraints:
  build: cuvs_bench.config.algos.constraints.cuvs_cagra_build
  search: cuvs_bench.config.algos.constraints.cuvs_cagra_search
groups:
  base:
    build:
      graph_degree: [32]
      intermediate_graph_degree: [64]
      cagra_build_algo: ["IVF_PQ"]
      b_pq_dim: [128]
      b_pq_bits: [8]
      b_n_lists: [1000, 2000]
      b_kmeans_n_iters: [10]
      s_n_probes: [2, 5, 10]
    search:
      itopk: [32, 64, 128, 256, 512, 768, 1024]
      search_width: [1 ,2 ,4 ,8, 16, 32]
      max_iterations: [16, 20, 24, 28, 32, 64, 128]
  test:
    build:
      graph_degree: [32]
      intermediate_graph_degree: [32]
      cagra_build_algo: ["IVF_PQ", "NN_DESCENT"]
    search:
      itopk: [32]
      search_width: [1, 2]
