name: faiss_cpu_hnsw_flat
groups:
  base:
    build:
      M: [16, 32]
      efConstruction: [32, 64, 128, 256, 512]
    search:
      bounded_queue: [False, True]
      check_relative_distance: [False, True]
      efSearch: [8, 16, 32, 64, 128, 256, 512, 768, 1024]
