name: faiss_gpu_ivf_pq
constraints:
  build: cuvs_bench.config.algos.constraints.faiss_gpu_ivf_pq_build
  search: cuvs_bench.config.algos.constraints.faiss_gpu_ivf_pq_search
groups:
  base:
    build:
      nlist: [50000, 100000]
      M: [96, 48]
      ratio: [10]
      usePrecomputed: [False, True]
      useFloat16: [True]
      use_cuvs: [False]
      bitsPerCode: [8]
    search:
      nprobe: [20, 30, 40, 50, 100, 200, 500, 1000]
      refine_ratio: [1, 2, 4]
  cuvs:
    build:
      nlist: [50000, 100000]
      M: [96, 48]
      ratio: [10]
      useFloat16: [False]
      use_cuvs: [True]
      bitsPerCode: [8, 6, 5]
    search:
      nprobe: [20, 30, 40, 50, 100, 200, 500, 1000]
      refine_ratio: [1, 2, 4]
