name: faiss_gpu_cagra_hnsw
constraints:
  build: cuvs_bench.config.algos.constraints.cuvs_cagra_build
groups:
  base:
    build:
      graph_degree: [32]
      intermediate_graph_degree: [64]
      cagra_build_algo: ["IVF_PQ"]
    search:
      efSearch: [40, 60, 80, 120, 200, 400, 600, 800]
