name: faiss_gpu_cagra_hnsw
constraints:
  build: cuvs_bench.config.algos.constraints.cuvs_cagra_build
groups:
  base:
    build:
      graph_degree: [32]
      intermediate_graph_degree: [64]
      cagra_build_algo: ["IVF_PQ"]
      b_pq_dim: [128]
      b_pq_bits: [8]
      b_n_lists: [1000, 2000]
      b_kmeans_n_iters: [10]
      s_n_probes: [2, 5]
      base_level_only: [False, True]
    search:
      efSearch: [16, 32, 64, 128, 256, 512, 768, 1024]
