#!/bin/bash

# SPDX-FileCopyrightText: Copyright (c) 2026, NVIDIA CORPORATION.
# SPDX-License-Identifier: Apache-2.0

# This script is a wrapper for clang-tidy that may be used with pre-commit.
# It requires a compilation database (compile_commands.json) generated by cmake.
# If no compilation database is found, the hook exits gracefully (exit 0) to
# avoid blocking commits or CI when the project hasn't been built.
#
# Only .cpp files are checked (CUDA .cu files require special handling with
# clang, see run-clang-tidy.py for the full CUDA-aware runner).
#
# Usage:
# bash run-clang-tidy-hook.sh infile [infile ...]

REPO_ROOT=$(git rev-parse --show-toplevel 2>/dev/null)
if [ -z "${REPO_ROOT}" ]; then
    echo "Warning: not inside a git repository. Skipping clang-tidy."
    exit 0
fi

BUILD_DIR="${REPO_ROOT}/cpp/build"
CDB="${BUILD_DIR}/compile_commands.json"

if [ ! -f "${CDB}" ]; then
    echo "Note: No compilation database found at ${CDB}."
    echo "      Build the project first to enable clang-tidy checks."
    echo "      Skipping clang-tidy."
    exit 0
fi

# Determine clang-tidy binary
CLANG_TIDY="${CLANG_TIDY:-clang-tidy}"
if ! command -v "${CLANG_TIDY}" &>/dev/null; then
    echo "Warning: ${CLANG_TIDY} not found. Skipping clang-tidy."
    exit 0
fi

# Filter: only check .cpp files that exist in the compilation database
HEADER_FILTER=".*cuvs/cpp/(src|include|bench|tests)/.*\.(cuh|h|hpp)$"
FAILED=0

for file in "$@"; do
    # Only process .cpp files
    case "${file}" in
        *.cpp) ;;
        *) continue ;;
    esac

    # Resolve to absolute path
    if [[ "${file}" != /* ]]; then
        file="${REPO_ROOT}/${file}"
    fi

    # Check if the file is in the compilation database
    if ! grep -q "\"${file}\"" "${CDB}" 2>/dev/null; then
        continue
    fi

    OUTPUT=$("${CLANG_TIDY}" -p "${BUILD_DIR}" \
        -header-filter="${HEADER_FILTER}" \
        --quiet \
        "${file}" 2>&1)

    # Filter output: only report actual clang-tidy check violations
    # (lines ending with [check-name] or [check-name,-warnings-as-errors]),
    # not clang-diagnostic errors from compilation issues.
    VIOLATIONS=$(echo "${OUTPUT}" | grep -E '\[(modernize-|google-|readability-)' || true)

    if [ -n "${VIOLATIONS}" ]; then
        echo "clang-tidy issues in ${file}:"
        echo "${VIOLATIONS}"
        echo ""
        FAILED=1
    fi
done

exit ${FAILED}
