/*
 * Copyright (c) 2024, NVIDIA CORPORATION.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

/*
 * NOTE: this file is generated by compute_distance_00_generate.py
 *
 * Make changes there and run in this directory:
 *
 * > python compute_distance_00_generate.py
 *
 */

#pragma once

#include "compute_distance_standard.cuh"
#include "compute_distance_vpq.cuh"

namespace cuvs::neighbors::cagra::detail {

extern template struct standard_dataset_descriptor_t<8, 64, float, uint32_t, float>;
extern template struct cagra_q_dataset_descriptor_t<8, 64, 8, 2, half, float, uint32_t, float>;
extern template struct cagra_q_dataset_descriptor_t<8, 64, 8, 4, half, float, uint32_t, float>;
extern template struct standard_dataset_descriptor_t<16, 128, float, uint32_t, float>;
extern template struct cagra_q_dataset_descriptor_t<16, 128, 8, 2, half, float, uint32_t, float>;
extern template struct cagra_q_dataset_descriptor_t<16, 128, 8, 4, half, float, uint32_t, float>;
extern template struct standard_dataset_descriptor_t<32, 256, float, uint32_t, float>;
extern template struct cagra_q_dataset_descriptor_t<32, 256, 8, 2, half, float, uint32_t, float>;
extern template struct cagra_q_dataset_descriptor_t<32, 256, 8, 4, half, float, uint32_t, float>;
extern template struct standard_dataset_descriptor_t<8, 64, half, uint32_t, float>;
extern template struct cagra_q_dataset_descriptor_t<8, 64, 8, 2, half, half, uint32_t, float>;
extern template struct cagra_q_dataset_descriptor_t<8, 64, 8, 4, half, half, uint32_t, float>;
extern template struct standard_dataset_descriptor_t<16, 128, half, uint32_t, float>;
extern template struct cagra_q_dataset_descriptor_t<16, 128, 8, 2, half, half, uint32_t, float>;
extern template struct cagra_q_dataset_descriptor_t<16, 128, 8, 4, half, half, uint32_t, float>;
extern template struct standard_dataset_descriptor_t<32, 256, half, uint32_t, float>;
extern template struct cagra_q_dataset_descriptor_t<32, 256, 8, 2, half, half, uint32_t, float>;
extern template struct cagra_q_dataset_descriptor_t<32, 256, 8, 4, half, half, uint32_t, float>;
extern template struct standard_dataset_descriptor_t<8, 64, int8_t, uint32_t, float>;
extern template struct cagra_q_dataset_descriptor_t<8, 64, 8, 2, half, int8_t, uint32_t, float>;
extern template struct cagra_q_dataset_descriptor_t<8, 64, 8, 4, half, int8_t, uint32_t, float>;
extern template struct standard_dataset_descriptor_t<16, 128, int8_t, uint32_t, float>;
extern template struct cagra_q_dataset_descriptor_t<16, 128, 8, 2, half, int8_t, uint32_t, float>;
extern template struct cagra_q_dataset_descriptor_t<16, 128, 8, 4, half, int8_t, uint32_t, float>;
extern template struct standard_dataset_descriptor_t<32, 256, int8_t, uint32_t, float>;
extern template struct cagra_q_dataset_descriptor_t<32, 256, 8, 2, half, int8_t, uint32_t, float>;
extern template struct cagra_q_dataset_descriptor_t<32, 256, 8, 4, half, int8_t, uint32_t, float>;
extern template struct standard_dataset_descriptor_t<8, 64, uint8_t, uint32_t, float>;
extern template struct cagra_q_dataset_descriptor_t<8, 64, 8, 2, half, uint8_t, uint32_t, float>;
extern template struct cagra_q_dataset_descriptor_t<8, 64, 8, 4, half, uint8_t, uint32_t, float>;
extern template struct standard_dataset_descriptor_t<16, 128, uint8_t, uint32_t, float>;
extern template struct cagra_q_dataset_descriptor_t<16, 128, 8, 2, half, uint8_t, uint32_t, float>;
extern template struct cagra_q_dataset_descriptor_t<16, 128, 8, 4, half, uint8_t, uint32_t, float>;
extern template struct standard_dataset_descriptor_t<32, 256, uint8_t, uint32_t, float>;
extern template struct cagra_q_dataset_descriptor_t<32, 256, 8, 2, half, uint8_t, uint32_t, float>;
extern template struct cagra_q_dataset_descriptor_t<32, 256, 8, 4, half, uint8_t, uint32_t, float>;
extern template struct standard_dataset_descriptor_t<8, 64, float, uint64_t, float>;
extern template struct cagra_q_dataset_descriptor_t<8, 64, 8, 2, half, float, uint64_t, float>;
extern template struct cagra_q_dataset_descriptor_t<8, 64, 8, 4, half, float, uint64_t, float>;
extern template struct standard_dataset_descriptor_t<16, 128, float, uint64_t, float>;
extern template struct cagra_q_dataset_descriptor_t<16, 128, 8, 2, half, float, uint64_t, float>;
extern template struct cagra_q_dataset_descriptor_t<16, 128, 8, 4, half, float, uint64_t, float>;
extern template struct standard_dataset_descriptor_t<32, 256, float, uint64_t, float>;
extern template struct cagra_q_dataset_descriptor_t<32, 256, 8, 2, half, float, uint64_t, float>;
extern template struct cagra_q_dataset_descriptor_t<32, 256, 8, 4, half, float, uint64_t, float>;
extern template struct standard_dataset_descriptor_t<8, 64, half, uint64_t, float>;
extern template struct cagra_q_dataset_descriptor_t<8, 64, 8, 2, half, half, uint64_t, float>;
extern template struct cagra_q_dataset_descriptor_t<8, 64, 8, 4, half, half, uint64_t, float>;
extern template struct standard_dataset_descriptor_t<16, 128, half, uint64_t, float>;
extern template struct cagra_q_dataset_descriptor_t<16, 128, 8, 2, half, half, uint64_t, float>;
extern template struct cagra_q_dataset_descriptor_t<16, 128, 8, 4, half, half, uint64_t, float>;
extern template struct standard_dataset_descriptor_t<32, 256, half, uint64_t, float>;
extern template struct cagra_q_dataset_descriptor_t<32, 256, 8, 2, half, half, uint64_t, float>;
extern template struct cagra_q_dataset_descriptor_t<32, 256, 8, 4, half, half, uint64_t, float>;
extern template struct standard_descriptor_spec<8, 64, float, uint32_t, float>;
extern template struct vpq_descriptor_spec<8, 64, 8, 2, half, float, uint32_t, float>;
extern template struct vpq_descriptor_spec<8, 64, 8, 4, half, float, uint32_t, float>;
extern template struct standard_descriptor_spec<16, 128, float, uint32_t, float>;
extern template struct vpq_descriptor_spec<16, 128, 8, 2, half, float, uint32_t, float>;
extern template struct vpq_descriptor_spec<16, 128, 8, 4, half, float, uint32_t, float>;
extern template struct standard_descriptor_spec<32, 256, float, uint32_t, float>;
extern template struct vpq_descriptor_spec<32, 256, 8, 2, half, float, uint32_t, float>;
extern template struct vpq_descriptor_spec<32, 256, 8, 4, half, float, uint32_t, float>;
extern template struct standard_descriptor_spec<8, 64, half, uint32_t, float>;
extern template struct vpq_descriptor_spec<8, 64, 8, 2, half, half, uint32_t, float>;
extern template struct vpq_descriptor_spec<8, 64, 8, 4, half, half, uint32_t, float>;
extern template struct standard_descriptor_spec<16, 128, half, uint32_t, float>;
extern template struct vpq_descriptor_spec<16, 128, 8, 2, half, half, uint32_t, float>;
extern template struct vpq_descriptor_spec<16, 128, 8, 4, half, half, uint32_t, float>;
extern template struct standard_descriptor_spec<32, 256, half, uint32_t, float>;
extern template struct vpq_descriptor_spec<32, 256, 8, 2, half, half, uint32_t, float>;
extern template struct vpq_descriptor_spec<32, 256, 8, 4, half, half, uint32_t, float>;
extern template struct standard_descriptor_spec<8, 64, int8_t, uint32_t, float>;
extern template struct vpq_descriptor_spec<8, 64, 8, 2, half, int8_t, uint32_t, float>;
extern template struct vpq_descriptor_spec<8, 64, 8, 4, half, int8_t, uint32_t, float>;
extern template struct standard_descriptor_spec<16, 128, int8_t, uint32_t, float>;
extern template struct vpq_descriptor_spec<16, 128, 8, 2, half, int8_t, uint32_t, float>;
extern template struct vpq_descriptor_spec<16, 128, 8, 4, half, int8_t, uint32_t, float>;
extern template struct standard_descriptor_spec<32, 256, int8_t, uint32_t, float>;
extern template struct vpq_descriptor_spec<32, 256, 8, 2, half, int8_t, uint32_t, float>;
extern template struct vpq_descriptor_spec<32, 256, 8, 4, half, int8_t, uint32_t, float>;
extern template struct standard_descriptor_spec<8, 64, uint8_t, uint32_t, float>;
extern template struct vpq_descriptor_spec<8, 64, 8, 2, half, uint8_t, uint32_t, float>;
extern template struct vpq_descriptor_spec<8, 64, 8, 4, half, uint8_t, uint32_t, float>;
extern template struct standard_descriptor_spec<16, 128, uint8_t, uint32_t, float>;
extern template struct vpq_descriptor_spec<16, 128, 8, 2, half, uint8_t, uint32_t, float>;
extern template struct vpq_descriptor_spec<16, 128, 8, 4, half, uint8_t, uint32_t, float>;
extern template struct standard_descriptor_spec<32, 256, uint8_t, uint32_t, float>;
extern template struct vpq_descriptor_spec<32, 256, 8, 2, half, uint8_t, uint32_t, float>;
extern template struct vpq_descriptor_spec<32, 256, 8, 4, half, uint8_t, uint32_t, float>;
extern template struct standard_descriptor_spec<8, 64, float, uint64_t, float>;
extern template struct vpq_descriptor_spec<8, 64, 8, 2, half, float, uint64_t, float>;
extern template struct vpq_descriptor_spec<8, 64, 8, 4, half, float, uint64_t, float>;
extern template struct standard_descriptor_spec<16, 128, float, uint64_t, float>;
extern template struct vpq_descriptor_spec<16, 128, 8, 2, half, float, uint64_t, float>;
extern template struct vpq_descriptor_spec<16, 128, 8, 4, half, float, uint64_t, float>;
extern template struct standard_descriptor_spec<32, 256, float, uint64_t, float>;
extern template struct vpq_descriptor_spec<32, 256, 8, 2, half, float, uint64_t, float>;
extern template struct vpq_descriptor_spec<32, 256, 8, 4, half, float, uint64_t, float>;
extern template struct standard_descriptor_spec<8, 64, half, uint64_t, float>;
extern template struct vpq_descriptor_spec<8, 64, 8, 2, half, half, uint64_t, float>;
extern template struct vpq_descriptor_spec<8, 64, 8, 4, half, half, uint64_t, float>;
extern template struct standard_descriptor_spec<16, 128, half, uint64_t, float>;
extern template struct vpq_descriptor_spec<16, 128, 8, 2, half, half, uint64_t, float>;
extern template struct vpq_descriptor_spec<16, 128, 8, 4, half, half, uint64_t, float>;
extern template struct standard_descriptor_spec<32, 256, half, uint64_t, float>;
extern template struct vpq_descriptor_spec<32, 256, 8, 2, half, half, uint64_t, float>;
extern template struct vpq_descriptor_spec<32, 256, 8, 4, half, half, uint64_t, float>;

using descriptor_instances =
  instance_selector<standard_descriptor_spec<8, 64, float, uint32_t, float>,
                    vpq_descriptor_spec<8, 64, 8, 2, half, float, uint32_t, float>,
                    vpq_descriptor_spec<8, 64, 8, 4, half, float, uint32_t, float>,
                    standard_descriptor_spec<16, 128, float, uint32_t, float>,
                    vpq_descriptor_spec<16, 128, 8, 2, half, float, uint32_t, float>,
                    vpq_descriptor_spec<16, 128, 8, 4, half, float, uint32_t, float>,
                    standard_descriptor_spec<32, 256, float, uint32_t, float>,
                    vpq_descriptor_spec<32, 256, 8, 2, half, float, uint32_t, float>,
                    vpq_descriptor_spec<32, 256, 8, 4, half, float, uint32_t, float>,
                    standard_descriptor_spec<8, 64, half, uint32_t, float>,
                    vpq_descriptor_spec<8, 64, 8, 2, half, half, uint32_t, float>,
                    vpq_descriptor_spec<8, 64, 8, 4, half, half, uint32_t, float>,
                    standard_descriptor_spec<16, 128, half, uint32_t, float>,
                    vpq_descriptor_spec<16, 128, 8, 2, half, half, uint32_t, float>,
                    vpq_descriptor_spec<16, 128, 8, 4, half, half, uint32_t, float>,
                    standard_descriptor_spec<32, 256, half, uint32_t, float>,
                    vpq_descriptor_spec<32, 256, 8, 2, half, half, uint32_t, float>,
                    vpq_descriptor_spec<32, 256, 8, 4, half, half, uint32_t, float>,
                    standard_descriptor_spec<8, 64, int8_t, uint32_t, float>,
                    vpq_descriptor_spec<8, 64, 8, 2, half, int8_t, uint32_t, float>,
                    vpq_descriptor_spec<8, 64, 8, 4, half, int8_t, uint32_t, float>,
                    standard_descriptor_spec<16, 128, int8_t, uint32_t, float>,
                    vpq_descriptor_spec<16, 128, 8, 2, half, int8_t, uint32_t, float>,
                    vpq_descriptor_spec<16, 128, 8, 4, half, int8_t, uint32_t, float>,
                    standard_descriptor_spec<32, 256, int8_t, uint32_t, float>,
                    vpq_descriptor_spec<32, 256, 8, 2, half, int8_t, uint32_t, float>,
                    vpq_descriptor_spec<32, 256, 8, 4, half, int8_t, uint32_t, float>,
                    standard_descriptor_spec<8, 64, uint8_t, uint32_t, float>,
                    vpq_descriptor_spec<8, 64, 8, 2, half, uint8_t, uint32_t, float>,
                    vpq_descriptor_spec<8, 64, 8, 4, half, uint8_t, uint32_t, float>,
                    standard_descriptor_spec<16, 128, uint8_t, uint32_t, float>,
                    vpq_descriptor_spec<16, 128, 8, 2, half, uint8_t, uint32_t, float>,
                    vpq_descriptor_spec<16, 128, 8, 4, half, uint8_t, uint32_t, float>,
                    standard_descriptor_spec<32, 256, uint8_t, uint32_t, float>,
                    vpq_descriptor_spec<32, 256, 8, 2, half, uint8_t, uint32_t, float>,
                    vpq_descriptor_spec<32, 256, 8, 4, half, uint8_t, uint32_t, float>,
                    standard_descriptor_spec<8, 64, float, uint64_t, float>,
                    vpq_descriptor_spec<8, 64, 8, 2, half, float, uint64_t, float>,
                    vpq_descriptor_spec<8, 64, 8, 4, half, float, uint64_t, float>,
                    standard_descriptor_spec<16, 128, float, uint64_t, float>,
                    vpq_descriptor_spec<16, 128, 8, 2, half, float, uint64_t, float>,
                    vpq_descriptor_spec<16, 128, 8, 4, half, float, uint64_t, float>,
                    standard_descriptor_spec<32, 256, float, uint64_t, float>,
                    vpq_descriptor_spec<32, 256, 8, 2, half, float, uint64_t, float>,
                    vpq_descriptor_spec<32, 256, 8, 4, half, float, uint64_t, float>,
                    standard_descriptor_spec<8, 64, half, uint64_t, float>,
                    vpq_descriptor_spec<8, 64, 8, 2, half, half, uint64_t, float>,
                    vpq_descriptor_spec<8, 64, 8, 4, half, half, uint64_t, float>,
                    standard_descriptor_spec<16, 128, half, uint64_t, float>,
                    vpq_descriptor_spec<16, 128, 8, 2, half, half, uint64_t, float>,
                    vpq_descriptor_spec<16, 128, 8, 4, half, half, uint64_t, float>,
                    standard_descriptor_spec<32, 256, half, uint64_t, float>,
                    vpq_descriptor_spec<32, 256, 8, 2, half, half, uint64_t, float>,
                    vpq_descriptor_spec<32, 256, 8, 4, half, half, uint64_t, float>>;

template <typename DataT, typename IndexT, typename DistanceT, typename DatasetT>
auto dataset_descriptor_init(const cagra::search_params& params,
                             const DatasetT& dataset,
                             rmm::cuda_stream_view stream)
  -> dataset_descriptor_host<DataT, IndexT, DistanceT>
{
  auto [init, priority] = descriptor_instances::select<DataT, IndexT, DistanceT>(params, dataset);
  if (init == nullptr || priority < 0) {
    RAFT_FAIL("No dataset descriptor instance compiled for this parameter combination.");
  }
  return init(params, dataset, stream);
}

}  // namespace cuvs::neighbors::cagra::detail
