/*
 * SPDX-FileCopyrightText: Copyright (c) 2024-2025, NVIDIA CORPORATION.
 * SPDX-License-Identifier: Apache-2.0
 */

/*
 * NOTE: this file is generated by compute_distance_00_generate.py
 *
 * Make changes there and run in this directory:
 *
 * > python compute_distance_00_generate.py
 *
 */

#include "compute_distance_vpq-impl.cuh"

namespace cuvs::neighbors::cagra::detail {

using namespace cuvs::distance;
template struct vpq_descriptor_spec<DistanceType::L2Expanded,
                                    32,
                                    512,
                                    8,
                                    4,
                                    half,
                                    int8_t,
                                    uint32_t,
                                    float,
                                    false>;

}  // namespace cuvs::neighbors::cagra::detail
