# SPDX-FileCopyrightText: Copyright (c) 2025-2026, NVIDIA CORPORATION.
# SPDX-License-Identifier: Apache-2.0
schema_version: 1

context:
  version: ${{ env.get("RAPIDS_PACKAGE_VERSION") }}
  minor_version: ${{ (version | split("."))[:2] | join(".") }}
  cuda_version: ${{ (env.get("RAPIDS_CUDA_VERSION") | split("."))[:2] | join(".") }}
  cuda_major: '${{ (env.get("RAPIDS_CUDA_VERSION") | split("."))[0] }}'
  date_string: '${{ env.get("RAPIDS_DATE_STRING") }}'
  head_rev: '${{ git.head_rev(".")[:8] }}'
  py_abi_min: ${{ env.get("RAPIDS_PY_VERSION") }}
  py_buildstring : ${{ py_abi_min | version_to_buildstring }}
  py_runtime_latest: "3.13"

package:
  name: cuvs-bench
  version: ${{ version }}

source:
  path: ../../..

build:
  python:
    version_independent: true
  string: cuda${{ cuda_major }}_cp${{ py_buildstring }}_abi3_${{ date_string }}_${{ head_rev }}
  script:
    content: |
      python -m pip install --no-build-isolation --no-deps --config-settings rapidsai.disable-cuda=true ./python/cuvs_bench

requirements:
  host:
    - cuda-version =${{ cuda_version }}
    - libcuvs =${{ version }}
    - libcuvs-bench-ann =${{ version }}
    - python =${{ py_abi_min }}
    - python-abi3 ${{ py_abi_min }}.*
    - pip
    - rapids-build-backend >=0.4.0,<0.5.0
    - rmm =${{ minor_version }}
    - setuptools>=77.0.0
  run:
    - ${{ pin_compatible("cuda-version", upper_bound="x", lower_bound="x") }}
    - click
    - cupy >=13.6.0
    - cuvs =${{ version }}
    - h5py ${{ h5py_version }}
    - libcuvs-bench-ann =${{ version }}
    - matplotlib-base>=3.9
    - pandas
    - pylibraft =${{ minor_version }}
    - python
    - pyyaml
    - requests
    # rmm is needed to determine if package is gpu-enabled
    - rmm =${{ minor_version }}
    - scikit-learn>=1.5
  ignore_run_exports:
    by_name:
      - cuda-version

tests:
  - package_contents:
      files:
        - site-packages/cuvs_bench/config/datasets/datasets.yaml
  - python:
      imports:
        - cuvs_bench
        - cuvs_bench.generate_groundtruth
        - cuvs_bench.get_dataset
        - cuvs_bench.plot
        - cuvs_bench.run
        - cuvs_bench.split_groundtruth
      python_version: ${{ py_runtime_latest }}.*
      pip_check: false

about:
  homepage: ${{ load_from_file("python/cuvs_bench/pyproject.toml").project.urls.Homepage }}
  license: ${{ load_from_file("python/cuvs_bench/pyproject.toml").project.license }}
  summary: ${{ load_from_file("python/cuvs_bench/pyproject.toml").project.description }}
