# Copyright (c) 2025, NVIDIA CORPORATION.
schema_version: 1

context:
  version: ${{ env.get("RAPIDS_PACKAGE_VERSION") }}
  minor_version: ${{ (version | split("."))[:2] | join(".") }}
  cuda_version: ${{ (env.get("RAPIDS_CUDA_VERSION") | split("."))[:2] | join(".") }}
  cuda_major: '${{ (env.get("RAPIDS_CUDA_VERSION") | split("."))[0] }}'
  date_string: '${{ env.get("RAPIDS_DATE_STRING") }}'
  py_version: ${{ env.get("RAPIDS_PY_VERSION") }}
  py_buildstring: ${{ py_version | version_to_buildstring }}
  head_rev: '${{ git.head_rev(".")[:8] }}'
  linux64: ${{ linux and x86_64 }}

package:
  name: cuvs-bench
  version: ${{ version }}

source:
  path: ../../..

build:
  string: cuda${{ cuda_major }}_py${{ py_buildstring }}_${{ date_string }}_${{ head_rev }}
  script:
    content: |
      python -m pip install --no-build-isolation --no-deps --config-settings rapidsai.disable-cuda=true ./python/cuvs_bench

requirements:
  host:
    - cuda-version =${{ cuda_version }}
    - libcuvs =${{ version }}
    - libcuvs-bench-ann =${{ version }}
    - python =${{ py_version }}
    - pip
    - rapids-build-backend >=0.4.0,<0.5.0.dev0
    - rmm =${{ minor_version }}
    - setuptools >=64.0.0
  run:
    - ${{ pin_compatible("cuda-version", upper_bound="x", lower_bound="x") }}
    - benchmark
    - click
    - cuda-cudart
    - cupy >=13.6.0
    - cuvs =${{ version }}
    - glog ${{ glog_version }}
    - h5py ${{ h5py_version }}
    - libcublas
    - libcuvs-bench-ann =${{ version }}
    - matplotlib-base>=3.9
    - pandas
    - pylibraft =${{ minor_version }}
    - python
    - pyyaml
    - requests
    # rmm is needed to determine if package is gpu-enabled
    - rmm =${{ minor_version }}
    - scikit-learn>=1.5
    - if: linux64
      then: mkl =2023
  ignore_run_exports:
    by_name:
      - cuda-version
      - cuda-cudart
      - glog
      - libaio
      - libboost
      - libcublas
      - mkl

tests:
  - package_contents:
      files:
        - lib/python*/site-packages/cuvs_bench/config/datasets/datasets.yaml

about:
  homepage: ${{ load_from_file("python/cuvs_bench/pyproject.toml").project.urls.Homepage }}
  license: ${{ load_from_file("python/cuvs_bench/pyproject.toml").project.license.text }}
  summary: ${{ load_from_file("python/cuvs_bench/pyproject.toml").project.description }}
