c_compiler_version:
  - 14

cxx_compiler_version:
  - 14

cuda_compiler:
  - cuda-nvcc

c_stdlib:
  - sysroot

c_stdlib_version:
  - "2.28"

cmake_version:
  - ">=3.30.4"

h5py_version:
  - ">=3.8.0"

nccl_version:
  - ">=2.19"
