# Copyright (c) 2022-2024, NVIDIA CORPORATION.

# Usage:
#   conda build . -c conda-forge -c nvidia -c rapidsai
{% set version = environ['RAPIDS_PACKAGE_VERSION'].lstrip('v') + environ.get('VERSION_SUFFIX', '') %}
{% set minor_version = version.split('.')[0] + '.' + version.split('.')[1] %}
{% set cuda_version = '.'.join(environ['RAPIDS_CUDA_VERSION'].split('.')[:2]) %}
{% set cuda_major = cuda_version.split('.')[0] %}
{% set date_string = environ['RAPIDS_DATE_STRING'] %}

package:
  name: libcuvs-split

source:
  path: ../../..

outputs:
  - name: libcuvs-static
    version: {{ version }}
    script: build_libcuvs_static.sh
    build:
      script_env: &script_env
        - AWS_ACCESS_KEY_ID
        - AWS_SECRET_ACCESS_KEY
        - AWS_SESSION_TOKEN
        - CMAKE_C_COMPILER_LAUNCHER
        - CMAKE_CUDA_COMPILER_LAUNCHER
        - CMAKE_CXX_COMPILER_LAUNCHER
        - CMAKE_GENERATOR
        - PARALLEL_LEVEL
        - RAPIDS_ARTIFACTS_DIR
        - SCCACHE_BUCKET
        - SCCACHE_IDLE_TIMEOUT
        - SCCACHE_REGION
        - SCCACHE_S3_KEY_PREFIX=libcuvs-aarch64 # [aarch64]
        - SCCACHE_S3_KEY_PREFIX=libcuvs-linux64 # [linux64]
        - SCCACHE_S3_USE_SSL
        - SCCACHE_S3_NO_CREDENTIALS
      number: {{ GIT_DESCRIBE_NUMBER }}
      string: cuda{{ cuda_major }}_{{ date_string }}_{{ GIT_DESCRIBE_HASH }}_{{ GIT_DESCRIBE_NUMBER }}
      ignore_run_exports_from:
        {% if cuda_major == "11" %}
        - {{ compiler('cuda11') }}
        {% else %}
        - {{ compiler('cuda') }}
        - cuda-cudart-dev
        - libcublas-dev
        - libcurand-dev
        - libcusolver-dev
        - libcusparse-dev
        {% endif %}
    requirements:
      build:
        - {{ compiler('c') }}
        - {{ compiler('cxx') }}
        {% if cuda_major == "11" %}
        - {{ compiler('cuda11') }} ={{ cuda_version }}
        {% else %}
        - {{ compiler('cuda') }}
        {% endif %}
        - cuda-version ={{ cuda_version }}
        - cmake {{ cmake_version }}
        - ninja
        - {{ stdlib("c") }}
      host:
        - libraft ={{ minor_version }}
        - cuda-version ={{ cuda_version }}
        {% if cuda_major == "11" %}
        - cuda-profiler-api {{ cuda11_cuda_profiler_api_host_version }}
        - libcublas {{ cuda11_libcublas_host_version }}
        - libcublas-dev {{ cuda11_libcublas_host_version }}
        - libcurand {{ cuda11_libcurand_host_version }}
        - libcurand-dev {{ cuda11_libcurand_host_version }}
        - libcusolver {{ cuda11_libcusolver_host_version }}
        - libcusolver-dev {{ cuda11_libcusolver_host_version }}
        - libcusparse {{ cuda11_libcusparse_host_version }}
        - libcusparse-dev {{ cuda11_libcusparse_host_version }}
        {% else %}
        - cuda-cudart-dev
        - cuda-profiler-api
        - libcublas-dev
        - libcurand-dev
        - libcusolver-dev
        - libcusparse-dev
        {% endif %}
      run:
        - libraft ={{ minor_version }}
        - {{ pin_compatible('cuda-version', max_pin='x', min_pin='x') }}
        {% if cuda_major != "11" %}
        - cuda-cudart
        - libcublas
        - libcurand
        - libcusolver
        - libcusparse
        {% endif %}
    about:
      home: https://rapids.ai/
      license: Apache-2.0
      summary: libcuvs static library
  - name: libcuvs
    version: {{ version }}
    script: build_libcuvs.sh
    build:
      script_env: *script_env
      number: {{ GIT_DESCRIBE_NUMBER }}
      string: cuda{{ cuda_major }}_{{ date_string }}_{{ GIT_DESCRIBE_HASH }}_{{ GIT_DESCRIBE_NUMBER }}
      ignore_run_exports_from:
        {% if cuda_major == "11" %}
        - {{ compiler('cuda11') }}
        {% else %}
        - {{ compiler('cuda') }}
        - cuda-cudart-dev
        - libcublas-dev
        - libcurand-dev
        - libcusolver-dev
        - libcusparse-dev
        {% endif %}
    requirements:
      build:
        - {{ compiler('c') }}
        - {{ compiler('cxx') }}
        {% if cuda_major == "11" %}
        - {{ compiler('cuda11') }} ={{ cuda_version }}
        {% else %}
        - {{ compiler('cuda') }}
        {% endif %}
        - cuda-version ={{ cuda_version }}
        - cmake {{ cmake_version }}
        - ninja
        - {{ stdlib("c") }}
      host:
        - libraft ={{ minor_version }}
        - cuda-version ={{ cuda_version }}
        {% if cuda_major == "11" %}
        - cuda-profiler-api {{ cuda11_cuda_profiler_api_host_version }}
        - libcublas {{ cuda11_libcublas_host_version }}
        - libcublas-dev {{ cuda11_libcublas_host_version }}
        - libcurand {{ cuda11_libcurand_host_version }}
        - libcurand-dev {{ cuda11_libcurand_host_version }}
        - libcusolver {{ cuda11_libcusolver_host_version }}
        - libcusolver-dev {{ cuda11_libcusolver_host_version }}
        - libcusparse {{ cuda11_libcusparse_host_version }}
        - libcusparse-dev {{ cuda11_libcusparse_host_version }}
        {% else %}
        - cuda-cudart-dev
        - cuda-profiler-api
        - libcublas-dev
        - libcurand-dev
        - libcusolver-dev
        - libcusparse-dev
        {% endif %}
      run:
        - libraft ={{ minor_version }}
        - {{ pin_compatible('cuda-version', max_pin='x', min_pin='x') }}
        {% if cuda_major != "11" %}
        - cuda-cudart
        - libcublas
        - libcurand
        - libcusolver
        - libcusparse
        {% endif %}
    about:
      home: https://rapids.ai/
      license: Apache-2.0
      summary: libcuvs library
  - name: libcuvs-tests
    version: {{ version }}
    script: build_libcuvs_tests.sh
    build:
      script_env: *script_env
      number: {{ GIT_DESCRIBE_NUMBER }}
      string: cuda{{ cuda_major }}_{{ date_string }}_{{ GIT_DESCRIBE_HASH }}_{{ GIT_DESCRIBE_NUMBER }}
      ignore_run_exports_from:
        {% if cuda_major == "11" %}
        - {{ compiler('cuda11') }}
        {% else %}
        - {{ compiler('cuda') }}
        - cuda-cudart-dev
        - libcublas-dev
        - libcurand-dev
        - libcusolver-dev
        - libcusparse-dev
        {% endif %}
    requirements:
      build:
        - {{ compiler('c') }}
        - {{ compiler('cxx') }}
        {% if cuda_major == "11" %}
        - {{ compiler('cuda11') }} ={{ cuda_version }}
        {% else %}
        - {{ compiler('cuda') }}
        {% endif %}
        - cuda-version ={{ cuda_version }}
        - cmake {{ cmake_version }}
        - ninja
        - {{ stdlib("c") }}
      host:
        - libraft ={{ minor_version }}
        - {{ pin_subpackage('libcuvs', exact=True) }}
        - cuda-version ={{ cuda_version }}
        - openblas # required by some CPU algos in benchmarks
        {% if cuda_major == "11" %}
        - cuda-profiler-api {{ cuda11_cuda_profiler_api_run_version }}
        - libcublas {{ cuda11_libcublas_host_version }}
        - libcublas-dev {{ cuda11_libcublas_host_version }}
        - libcurand {{ cuda11_libcurand_host_version }}
        - libcurand-dev {{ cuda11_libcurand_host_version }}
        - libcusolver {{ cuda11_libcusolver_host_version }}
        - libcusolver-dev {{ cuda11_libcusolver_host_version }}
        - libcusparse {{ cuda11_libcusparse_host_version }}
        - libcusparse-dev {{ cuda11_libcusparse_host_version }}
        {% else %}
        - cuda-cudart-dev
        - cuda-profiler-api
        - libcublas-dev
        - libcurand-dev
        - libcusolver-dev
        - libcusparse-dev
        {% endif %}
      run:
        - {{ pin_compatible('cuda-version', max_pin='x', min_pin='x') }}
        {% if cuda_major == "11" %}
        - cudatoolkit
        {% else %}
        - cuda-cudart
        - libcublas
        - libcurand
        - libcusolver
        - libcusparse
        {% endif %}
        - libraft ={{ minor_version }}
        - {{ pin_subpackage('libcuvs', exact=True) }}
    about:
      home: https://rapids.ai/
      license: Apache-2.0
      summary: libcuvs tests
  - name: libcuvs-examples
    version: {{ version }}
    script: build_libcuvs_examples.sh
    build:
      script_env: *script_env
      number: {{ GIT_DESCRIBE_NUMBER }}
      string: cuda{{ cuda_major }}_{{ date_string }}_{{ GIT_DESCRIBE_HASH }}_{{ GIT_DESCRIBE_NUMBER }}
      ignore_run_exports_from:
        {% if cuda_major == "11" %}
        - {{ compiler('cuda11') }}
        {% else %}
        - {{ compiler('cuda') }}
        - cuda-cudart-dev
        - libcublas-dev
        {% endif %}
    requirements:
      build:
        - {{ compiler('c') }}
        - {{ compiler('cxx') }}
        {% if cuda_major == "11" %}
        - {{ compiler('cuda11') }} ={{ cuda_version }}
        {% else %}
        - {{ compiler('cuda') }}
        {% endif %}
        - cuda-version ={{ cuda_version }}
        - cmake {{ cmake_version }}
        - ninja
        - {{ stdlib("c") }}
      host:
        - libraft ={{ minor_version }}
        - {{ pin_subpackage('libcuvs', exact=True) }}
        - cuda-version ={{ cuda_version }}
        {% if cuda_major == "11" %}
        - cuda-profiler-api {{ cuda11_cuda_profiler_api_run_version }}
        - libcublas {{ cuda11_libcublas_host_version }}
        - libcublas-dev {{ cuda11_libcublas_host_version }}
        {% else %}
        - cuda-cudart-dev
        - cuda-profiler-api
        - libcublas-dev
        {% endif %}
      run:
        - {{ pin_compatible('cuda-version', max_pin='x', min_pin='x') }}
        {% if cuda_major == "11" %}
        - cudatoolkit
        {% else %}
        - cuda-cudart
        - libcublas
        {% endif %}
        - libraft ={{ minor_version }}
        - {{ pin_subpackage('libcuvs', exact=True) }}
    about:
      home: https://rapids.ai/
      license: Apache-2.0
      summary: libcuvs examples
