# SPDX-FileCopyrightText: Copyright (c) 2025-2026, NVIDIA CORPORATION.
# SPDX-License-Identifier: Apache-2.0
schema_version: 1

context:
  version: ${{ env.get("RAPIDS_PACKAGE_VERSION") }}
  minor_version: ${{ (version | split("."))[:2] | join(".") }}
  cuda_version: ${{ (env.get("RAPIDS_CUDA_VERSION") | split("."))[:2] | join(".") }}
  cuda_major: '${{ (env.get("RAPIDS_CUDA_VERSION") | split("."))[0] }}'
  date_string: '${{ env.get("RAPIDS_DATE_STRING") }}'
  head_rev: '${{ git.head_rev(".")[:8] }}'
  linux64: ${{ linux and x86_64 }}

recipe:
  name: libcuvs-split

cache:
  source:
    path: ../../..

  build:
    script:
      content: |

        # Remove `-fdebug-prefix-map` line from CFLAGS and CXXFLAGS so the
        # incrementing version number in the compile line doesn't break the
        # cache
        set -x
        export CFLAGS=$(echo $CFLAGS | sed -E 's@\-fdebug\-prefix\-map[^ ]*@@g')
        export CXXFLAGS=$(echo $CXXFLAGS | sed -E 's@\-fdebug\-prefix\-map[^ ]*@@g')
        set +x

        ./build.sh libcuvs bench-ann tests --allgpuarch --build-metrics=compile_lib --incl-cache-stats --no-nvtx -n

      secrets:
        - AWS_ACCESS_KEY_ID
        - AWS_SECRET_ACCESS_KEY
        - AWS_SESSION_TOKEN
        - SCCACHE_DIST_AUTH_TOKEN
      env:
        CMAKE_C_COMPILER_LAUNCHER: ${{ env.get("CMAKE_C_COMPILER_LAUNCHER") }}
        CMAKE_CUDA_COMPILER_LAUNCHER: ${{ env.get("CMAKE_CUDA_COMPILER_LAUNCHER") }}
        CMAKE_CXX_COMPILER_LAUNCHER: ${{ env.get("CMAKE_CXX_COMPILER_LAUNCHER") }}
        CMAKE_GENERATOR: ${{ env.get("CMAKE_GENERATOR") }}
        NVCC_APPEND_FLAGS: ${{ env.get("NVCC_APPEND_FLAGS", default="") }}
        PARALLEL_LEVEL: ${{ env.get("PARALLEL_LEVEL", default="8") }}
        RAPIDS_ARTIFACTS_DIR: ${{ env.get("RAPIDS_ARTIFACTS_DIR", default="") }}
        SCCACHE_BUCKET: ${{ env.get("SCCACHE_BUCKET", default="") }}
        SCCACHE_DIST_AUTH_TYPE: ${{ env.get("SCCACHE_DIST_AUTH_TYPE", default="token") }}
        SCCACHE_DIST_FALLBACK_TO_LOCAL_COMPILE: ${{ env.get("SCCACHE_DIST_FALLBACK_TO_LOCAL_COMPILE", default="false") }}
        SCCACHE_DIST_MAX_RETRIES: ${{ env.get("SCCACHE_DIST_MAX_RETRIES", default="inf") }}
        SCCACHE_DIST_REQUEST_TIMEOUT: ${{ env.get("SCCACHE_DIST_REQUEST_TIMEOUT", default="7140") }}
        SCCACHE_DIST_SCHEDULER_URL: ${{ env.get("SCCACHE_DIST_SCHEDULER_URL", default="") }}
        SCCACHE_ERROR_LOG: ${{ env.get("SCCACHE_ERROR_LOG", default="/tmp/sccache.log") }}
        SCCACHE_IDLE_TIMEOUT: ${{ env.get("SCCACHE_IDLE_TIMEOUT", default="0") }}
        SCCACHE_NO_CACHE: ${{ env.get("SCCACHE_NO_CACHE", default="") }}
        SCCACHE_RECACHE: ${{ env.get("SCCACHE_RECACHE", default="") }}
        SCCACHE_REGION: ${{ env.get("SCCACHE_REGION", default="") }}
        SCCACHE_S3_KEY_PREFIX: libcuvs/${{ env.get("RAPIDS_CONDA_ARCH") }}/cuda${{ cuda_major }}
        SCCACHE_S3_NO_CREDENTIALS: ${{ env.get("SCCACHE_S3_NO_CREDENTIALS", default="false") }}
        SCCACHE_S3_PREPROCESSOR_CACHE_KEY_PREFIX: libcuvs/${{ env.get("RAPIDS_CONDA_ARCH") }}/cuda${{ cuda_major }}/conda/preprocessor-cache
        SCCACHE_S3_USE_PREPROCESSOR_CACHE_MODE: ${{ env.get("SCCACHE_S3_USE_PREPROCESSOR_CACHE_MODE", default="true") }}
        SCCACHE_S3_USE_SSL: ${{ env.get("SCCACHE_S3_USE_SSL", default="true") }}
        SCCACHE_SERVER_LOG: ${{ env.get("SCCACHE_SERVER_LOG", default="sccache=debug") }}
  requirements:
    build:
      - ${{ compiler("c") }}
      - ${{ compiler("cxx") }}
      - ${{ compiler("cuda") }}
      - cuda-version =${{ cuda_version }}
      - cmake ${{ cmake_version }}
      - ninja
      - ${{ stdlib("c") }}
    host:
      - if: cuda_major == "13"
        then:
          - libnvjitlink-dev
          - cuda-nvrtc-dev
      - librmm =${{ minor_version }}
      - libraft-headers =${{ minor_version }}
      - nccl ${{ nccl_version }}
      - cuda-version =${{ cuda_version }}
      - cuda-cudart-dev
      - cuda-profiler-api
      - libcublas-dev
      - libcurand-dev
      - libcusolver-dev
      - libcusparse-dev
      # These are used for bench-ann
      - openblas
      - if: linux64
        then:
          - libaio
          - libboost-devel =1.87
          - mkl-devel =2023

outputs:
  - package:
      name: libcuvs-headers
      version: ${{ version }}
    build:
      string: cuda${{ cuda_major }}_${{ date_string }}_${{ head_rev }}
      dynamic_linking:
        overlinking_behavior: "error"
      prefix_detection:
        ignore_binary_files: True
      script:
        content: |
          cmake --install cpp/build --component cuvs_cpp_headers
    requirements:
      build:
        - cmake ${{ cmake_version }}
        - ${{ stdlib("c") }}
      host:
        - librmm =${{ minor_version }}
        - libraft-headers =${{ minor_version }}
        - nccl ${{ nccl_version }}
        - cuda-version =${{ cuda_version }}
        - cuda-cudart-dev
        - cuda-profiler-api
        - libcublas-dev
        - libcurand-dev
        - libcusolver-dev
        - libcusparse-dev
        - if: cuda_major == "13"
          then:
            - libnvjitlink-dev
            - cuda-nvrtc-dev
      run:
        - ${{ pin_compatible("cuda-version", upper_bound="x", lower_bound="x") }}
        - libraft-headers =${{ minor_version }}
        - librmm =${{ minor_version }}
        - nccl
        - cuda-cudart
        - libcublas
        - libcurand
        - libcusolver
        - libcusparse
        - if: cuda_major == "13"
          then:
            - libnvjitlink
            - cuda-nvrtc
      ignore_run_exports:
        by_name:
          - cuda-cudart
          - cuda-version
          - libaio
          - libboost
          - libcublas
          - libcurand
          - libcusolver
          - libcusparse
          - librmm
          - mkl
          - nccl
          - if: cuda_major == "13"
            then:
              - libnvjitlink
              - cuda-nvrtc
    about:
      homepage: ${{ load_from_file("python/libcuvs/pyproject.toml").project.urls.Homepage }}
      license: ${{ load_from_file("python/libcuvs/pyproject.toml").project.license }}
      summary: ${{ load_from_file("python/libcuvs/pyproject.toml").project.description }}

  - package:
      name: libcuvs
      version: ${{ version }}
    build:
      string: cuda${{ cuda_major }}_${{ date_string }}_${{ head_rev }}
      dynamic_linking:
        overlinking_behavior: "error"
      prefix_detection:
        ignore_binary_files: True
      script:
        content: |
          cmake --install cpp/build --component cuvs
          cmake --install cpp/build --component cuvs_shared
          cmake --install cpp/build --component c_api
          cmake --install cpp/build --component hnswlib
    requirements:
      build:
        - cmake ${{ cmake_version }}
        - ${{ stdlib("c") }}
      host:
        - ${{ pin_subpackage("libcuvs-headers", exact=True) }}
        - librmm =${{ minor_version }}
        - libraft-headers =${{ minor_version }}
        - nccl ${{ nccl_version }}
        - cuda-version =${{ cuda_version }}
        - cuda-cudart-dev
        - cuda-profiler-api
        - libcublas-dev
        - libcurand-dev
        - libcusolver-dev
        - libcusparse-dev
        - if: cuda_major == "13"
          then:
            - libnvjitlink-dev
            - cuda-nvrtc-dev
      run:
        - ${{ pin_compatible("cuda-version", upper_bound="x", lower_bound="x") }}
        - ${{ pin_subpackage("libcuvs-headers", exact=True) }}
        - libraft-headers =${{ minor_version }}
        - librmm =${{ minor_version }}
        - nccl
        - cuda-cudart
        - libcublas
        - libcurand
        - libcusolver
        - libcusparse
        - if: cuda_major == "13"
          then:
            - libnvjitlink
            - cuda-nvrtc
      ignore_run_exports:
        by_name:
          - cuda-cudart
          - cuda-version
          - libaio
          - libboost
          - libcublas
          - libcurand
          - libcusolver
          - libcusparse
          - librmm
          - mkl
          - nccl
          - if: cuda_major == "13"
            then:
              - libnvjitlink
              - cuda-nvrtc
    about:
      homepage: ${{ load_from_file("python/libcuvs/pyproject.toml").project.urls.Homepage }}
      license: ${{ load_from_file("python/libcuvs/pyproject.toml").project.license }}
      summary: ${{ load_from_file("python/libcuvs/pyproject.toml").project.description }}

  - package:
      name: libcuvs-static
      version: ${{ version }}
    build:
      string: cuda${{ cuda_major }}_${{ date_string }}_${{ head_rev }}
      dynamic_linking:
        overlinking_behavior: "error"
      prefix_detection:
        ignore_binary_files: True
      script:
        content: |
          cmake --install cpp/build --component cuvs_static
          cmake --install cpp/build --component hnswlib
    requirements:
      build:
        - cmake ${{ cmake_version }}
        - ${{ stdlib("c") }}
      host:
        - ${{ pin_subpackage("libcuvs-headers", exact=True) }}
        - librmm =${{ minor_version }}
        - libraft-headers =${{ minor_version }}
        - nccl ${{ nccl_version }}
        - cuda-version =${{ cuda_version }}
        - cuda-cudart-dev
        - cuda-profiler-api
        - libcublas-dev
        - libcurand-dev
        - libcusolver-dev
        - libcusparse-dev
        - if: cuda_major == "13"
          then:
            - libnvjitlink-dev
            - cuda-nvrtc-dev
      run:
        - ${{ pin_compatible("cuda-version", upper_bound="x", lower_bound="x") }}
        - ${{ pin_subpackage("libcuvs-headers", exact=True) }}
        - libraft-headers =${{ minor_version }}
        - librmm =${{ minor_version }}
        - nccl
        - cuda-cudart
        - libcublas
        - libcurand
        - libcusolver
        - libcusparse
        - if: cuda_major == "13"
          then:
            - libnvjitlink
            - cuda-nvrtc
      ignore_run_exports:
        by_name:
          - cuda-cudart
          - cuda-version
          - libaio
          - libboost
          - libcublas
          - libcurand
          - libcusolver
          - libcusparse
          - if: cuda_major == "13"
            then:
              - libnvjitlink
              - cuda-nvrtc
          - librmm
          - mkl
          - nccl
    about:
      homepage: ${{ load_from_file("python/libcuvs/pyproject.toml").project.urls.Homepage }}
      license: ${{ load_from_file("python/libcuvs/pyproject.toml").project.license }}
      summary: ${{ load_from_file("python/libcuvs/pyproject.toml").project.description }}

  - package:
      name: libcuvs-tests
      version: ${{ version }}
    build:
      script: cmake --install cpp/build --component testing
      string: cuda${{ cuda_major }}_${{ date_string }}_${{ head_rev }}
      dynamic_linking:
        overlinking_behavior: "error"
      prefix_detection:
        ignore_binary_files: True
    requirements:
      build:
        - cmake ${{ cmake_version }}
        - ${{ stdlib("c") }}
      host:
        - librmm =${{ minor_version }}
        - libraft-headers =${{ minor_version }}
        - nccl ${{ nccl_version }}
        - ${{ pin_subpackage("libcuvs-headers", exact=True) }}
        - ${{ pin_subpackage("libcuvs", exact=True) }}
        - cuda-version =${{ cuda_version }}
        - openblas  # required by some CPU algos in benchmarks
        - cuda-cudart-dev
        - cuda-profiler-api
        - libcublas-dev
        - libcurand-dev
        - libcusolver-dev
        - libcusparse-dev
      run:
        - ${{ pin_subpackage("libcuvs-headers", exact=True) }}
        - ${{ pin_subpackage("libcuvs", exact=True) }}
        - ${{ pin_compatible("cuda-version", upper_bound="x", lower_bound="x") }}
        - libraft-headers =${{ minor_version }}
        - nccl
        - cuda-cudart
        - libcublas
        - libcurand
        - libcusolver
        - libcusparse
      ignore_run_exports:
        by_name:
          - cuda-cudart
          - cuda-version
          - libaio
          - libboost
          - libcublas
          - libcurand
          - libcusolver
          - libcusparse
          - librmm
          - mkl
          - nccl
          - if: cuda_major == "13"
            then:
              - cuda-nvrtc
              - libnvjitlink
    about:
      homepage: ${{ load_from_file("python/libcuvs/pyproject.toml").project.urls.Homepage }}
      license: ${{ load_from_file("python/libcuvs/pyproject.toml").project.license }}
      summary: libcuvs test executables

  - package:
      name: libcuvs-examples
      version: ${{ version }}
    build:
      string: cuda${{ cuda_major }}_${{ date_string }}_${{ head_rev }}
      dynamic_linking:
        overlinking_behavior: "error"
      prefix_detection:
        ignore_binary_files: True
      script:
        content: |
          # Remove `-fdebug-prefix-map` line from CFLAGS and CXXFLAGS so the
          # incrementing version number in the compile line doesn't break the
          # cache
          set -x
          export CFLAGS=$(echo $CFLAGS | sed -E 's@\-fdebug\-prefix\-map[^ ]*@@g')
          export CXXFLAGS=$(echo $CXXFLAGS | sed -E 's@\-fdebug\-prefix\-map[^ ]*@@g')
          set +x

          ./build.sh examples

        secrets:
          - AWS_ACCESS_KEY_ID
          - AWS_SECRET_ACCESS_KEY
          - AWS_SESSION_TOKEN
        env:
          CMAKE_C_COMPILER_LAUNCHER: ${{ env.get("CMAKE_C_COMPILER_LAUNCHER") }}
          CMAKE_CUDA_COMPILER_LAUNCHER: ${{ env.get("CMAKE_CUDA_COMPILER_LAUNCHER") }}
          CMAKE_CXX_COMPILER_LAUNCHER: ${{ env.get("CMAKE_CXX_COMPILER_LAUNCHER") }}
          CMAKE_GENERATOR: ${{ env.get("CMAKE_GENERATOR") }}
          NVCC_APPEND_FLAGS: ${{ env.get("NVCC_APPEND_FLAGS", default="") }}
          PARALLEL_LEVEL: ${{ env.get("PARALLEL_LEVEL", default="8") }}
          RAPIDS_ARTIFACTS_DIR: ${{ env.get("RAPIDS_ARTIFACTS_DIR", default="") }}
          SCCACHE_BUCKET: ${{ env.get("SCCACHE_BUCKET", default="") }}
          SCCACHE_DIST_AUTH_TYPE: ${{ env.get("SCCACHE_DIST_AUTH_TYPE", default="token") }}
          SCCACHE_DIST_FALLBACK_TO_LOCAL_COMPILE: ${{ env.get("SCCACHE_DIST_FALLBACK_TO_LOCAL_COMPILE", default="false") }}
          SCCACHE_DIST_MAX_RETRIES: ${{ env.get("SCCACHE_DIST_MAX_RETRIES", default="inf") }}
          SCCACHE_DIST_REQUEST_TIMEOUT: ${{ env.get("SCCACHE_DIST_REQUEST_TIMEOUT", default="7140") }}
          SCCACHE_DIST_SCHEDULER_URL: ${{ env.get("SCCACHE_DIST_SCHEDULER_URL", default="") }}
          SCCACHE_ERROR_LOG: ${{ env.get("SCCACHE_ERROR_LOG", default="/tmp/sccache.log") }}
          SCCACHE_IDLE_TIMEOUT: ${{ env.get("SCCACHE_IDLE_TIMEOUT", default="0") }}
          SCCACHE_NO_CACHE: ${{ env.get("SCCACHE_NO_CACHE", default="") }}
          SCCACHE_RECACHE: ${{ env.get("SCCACHE_RECACHE", default="") }}
          SCCACHE_REGION: ${{ env.get("SCCACHE_REGION", default="") }}
          SCCACHE_S3_KEY_PREFIX: libcuvs/${{ env.get("RAPIDS_CONDA_ARCH") }}/cuda${{ cuda_major }}
          SCCACHE_S3_NO_CREDENTIALS: ${{ env.get("SCCACHE_S3_NO_CREDENTIALS", default="false") }}
          SCCACHE_S3_PREPROCESSOR_CACHE_KEY_PREFIX: libcuvs/${{ env.get("RAPIDS_CONDA_ARCH") }}/cuda${{ cuda_major }}/conda/preprocessor-cache
          SCCACHE_S3_USE_PREPROCESSOR_CACHE_MODE: ${{ env.get("SCCACHE_S3_USE_PREPROCESSOR_CACHE_MODE", default="true") }}
          SCCACHE_S3_USE_SSL: ${{ env.get("SCCACHE_S3_USE_SSL", default="true") }}
          SCCACHE_SERVER_LOG: ${{ env.get("SCCACHE_SERVER_LOG", default="sccache=debug") }}
    requirements:
      build:
        - ${{ compiler("c") }}
        - ${{ compiler("cxx") }}
        - ${{ compiler("cuda") }}
        - cuda-version =${{ cuda_version }}
        - cmake ${{ cmake_version }}
        - ninja
        - ${{ stdlib("c") }}
      host:
        - ${{ pin_subpackage("libcuvs-headers", exact=True) }}
        - ${{ pin_subpackage("libcuvs", exact=True) }}
        - cuda-version =${{ cuda_version }}
        - libraft-headers =${{ minor_version }}
        - librmm =${{ minor_version }}
        - nccl ${{ nccl_version }}
        - cuda-cudart-dev
        - cuda-profiler-api
        - libcublas-dev
        - libcurand-dev
        - libcusolver-dev
        - libcusparse-dev
        - if: cuda_major == "13"
          then:
            - libnvjitlink-dev
            - cuda-nvrtc-dev
      run:
        - ${{ pin_subpackage("libcuvs-headers", exact=True) }}
        - ${{ pin_subpackage("libcuvs", exact=True) }}
        - ${{ pin_compatible("cuda-version", upper_bound="x", lower_bound="x") }}
        - nccl
        - cuda-cudart
        - libcublas
        - libcurand
        - libcusolver
        - libcusparse
        - if: cuda_major == "13"
          then:
            - libnvjitlink
            - cuda-nvrtc
      ignore_run_exports:
        by_name:
          - cuda-cudart
          - cuda-version
          - libaio
          - libboost
          - libcublas
          - libcurand
          - libcusolver
          - libcusparse
          - if: cuda_major == "13"
            then:
              - libnvjitlink
              - cuda-nvrtc
          - librmm
          - mkl
          - nccl
    about:
      homepage: ${{ load_from_file("python/libcuvs/pyproject.toml").project.urls.Homepage }}
      license: ${{ load_from_file("python/libcuvs/pyproject.toml").project.license }}
      summary: libcuvs example executables

  - package:
      name: libcuvs-bench-ann
      version: ${{ version }}
    build:
      script:
        content: |
          cmake --install cpp/build --component ann_bench

          if [ "$RAPIDS_CONDA_ARCH" != "aarch64" ]; then
            # Need this so from the diskann compile, but there isn't a
            # component associated with it. Probably a better way to do this.
            cp cpp/build/_deps/diskann-build/src/libdiskann.so $PREFIX/lib/
          fi
      string: cuda${{ cuda_major }}_${{ date_string }}_${{ head_rev }}
      dynamic_linking:
        overlinking_behavior: "error"
      prefix_detection:
        ignore_binary_files: True
    requirements:
      build:
        - cmake ${{ cmake_version }}
        - ${{ stdlib("c") }}
      host:
        - ${{ pin_subpackage("libcuvs-headers", exact=True) }}
        - ${{ pin_subpackage("libcuvs", exact=True) }}
        - cuda-cudart-dev
        - cuda-profiler-api
        - cuda-version =${{ cuda_version }}
        - libcublas-dev
        - libcurand-dev
        - libcusolver-dev
        - libcusparse-dev
        - libgomp
        - libraft-headers =${{ minor_version }}
        - librmm =${{ minor_version }}
        - nccl ${{ nccl_version }}
        - openblas  # required by some CPU algos in benchmarks
        - if: linux64
          then:
            - libaio
            - libboost-devel =1.87
            - mkl-devel =2023
      run:
        - ${{ pin_subpackage("libcuvs-headers", exact=True) }}
        - ${{ pin_subpackage("libcuvs", exact=True) }}
        - ${{ pin_compatible("cuda-version", upper_bound="x", lower_bound="x") }}
        - cuda-cudart
        - libcublas
        - libcurand
        - libcusolver
        - libcusparse
        - libraft-headers =${{ minor_version }}
        - nccl
        - if: linux64
          then: mkl =2023
      ignore_run_exports:
        by_name:
          - cuda-cudart
          - cuda-version
          - libcublas
          - libcurand
          - libcusolver
          - libcusparse
          - librmm
          - mkl
          - nccl
          - if: cuda_major == "13"
            then:
              - cuda-nvrtc
              - libnvjitlink
    about:
      homepage: ${{ load_from_file("python/cuvs_bench/pyproject.toml").project.urls.Homepage }}
      license: ${{ load_from_file("python/cuvs_bench/pyproject.toml").project.license }}
      summary: libcuvs benchmark
