dataset:
  base_file: deep-1B/base.1B.fbin
  distance: inner_product
  groundtruth_neighbors_file: deep-1B/groundtruth.neighbors.ibin
  name: deep-1B
  query_file: deep-1B/query.public.10K.fbin
index:
- algo: faiss_gpu_ivf_pq
  build_param:
    M: 48
    nlist: 50000
  file: deep-1B/faiss_gpu_ivf_pq/M48-nlist50K
  name: faiss_gpu_ivf_pq.M48-nlist50K
  search_params:
  - nprobe: 1
  - nprobe: 5
  - nprobe: 10
  - nprobe: 50
  - nprobe: 100
  - nprobe: 200
  - nprobe: 500
  - nprobe: 1000
  - nprobe: 2000
search_basic_param:
  batch_size: 10000
  k: 10
