dataset:
  base_file: lastfm-65-angular/base.fbin
  distance: euclidean
  name: lastfm-65-angular
  query_file: lastfm-65-angular/query.fbin
index:
- algo: hnswlib
  build_param:
    M: 12
    efConstruction: 500
    numThreads: 32
  file: index/lastfm-65-angular/hnswlib/M12
  name: hnswlib.M12
  search_params:
  - ef: 10
  - ef: 20
  - ef: 40
  - ef: 60
  - ef: 80
  - ef: 120
  - ef: 200
  - ef: 400
  - ef: 600
  - ef: 800
  search_result_file: result/lastfm-65-angular/hnswlib/M12
- algo: hnswlib
  build_param:
    M: 16
    efConstruction: 500
    numThreads: 32
  file: index/lastfm-65-angular/hnswlib/M16
  name: hnswlib.M16
  search_params:
  - ef: 10
  - ef: 20
  - ef: 40
  - ef: 60
  - ef: 80
  - ef: 120
  - ef: 200
  - ef: 400
  - ef: 600
  - ef: 800
  search_result_file: result/lastfm-65-angular/hnswlib/M16
- algo: hnswlib
  build_param:
    M: 24
    efConstruction: 500
    numThreads: 32
  file: index/lastfm-65-angular/hnswlib/M24
  name: hnswlib.M24
  search_params:
  - ef: 10
  - ef: 20
  - ef: 40
  - ef: 60
  - ef: 80
  - ef: 120
  - ef: 200
  - ef: 400
  - ef: 600
  - ef: 800
  search_result_file: result/lastfm-65-angular/hnswlib/M24
- algo: hnswlib
  build_param:
    M: 36
    efConstruction: 500
    numThreads: 32
  file: index/lastfm-65-angular/hnswlib/M36
  name: hnswlib.M36
  search_params:
  - ef: 10
  - ef: 20
  - ef: 40
  - ef: 60
  - ef: 80
  - ef: 120
  - ef: 200
  - ef: 400
  - ef: 600
  - ef: 800
  search_result_file: result/lastfm-65-angular/hnswlib/M36
- algo: raft_bfknn
  build_param: {}
  file: index/lastfm-65-angular/raft_bfknn/bfknn
  name: raft_bfknn
  search_params:
  - probe: 1
  search_result_file: result/lastfm-65-angular/raft_bfknn/bfknn
- algo: faiss_gpu_ivf_flat
  build_param:
    nlist: 1024
  file: index/lastfm-65-angular/faiss_gpu_ivf_flat/nlist1024
  name: faiss_gpu_ivf_flat.nlist1024
  search_params:
  - nprobe: 1
  - nprobe: 5
  - nprobe: 10
  - nprobe: 50
  - nprobe: 100
  - nprobe: 200
  - nprobe: 500
  - nprobe: 1000
  search_result_file: result/lastfm-65-angular/faiss_gpu_ivf_flat/nlist1024
- algo: faiss_gpu_ivf_flat
  build_param:
    nlist: 2048
  file: index/lastfm-65-angular/faiss_gpu_ivf_flat/nlist2048
  name: faiss_gpu_ivf_flat.nlist2048
  search_params:
  - nprobe: 1
  - nprobe: 5
  - nprobe: 10
  - nprobe: 50
  - nprobe: 100
  - nprobe: 200
  - nprobe: 500
  - nprobe: 1000
  search_result_file: result/lastfm-65-angular/faiss_gpu_ivf_flat/nlist2048
- algo: faiss_gpu_ivf_flat
  build_param:
    nlist: 4096
  file: index/lastfm-65-angular/faiss_gpu_ivf_flat/nlist4096
  name: faiss_gpu_ivf_flat.nlist4096
  search_params:
  - nprobe: 1
  - nprobe: 5
  - nprobe: 10
  - nprobe: 50
  - nprobe: 100
  - nprobe: 200
  - nprobe: 500
  - nprobe: 1000
  search_result_file: result/lastfm-65-angular/faiss_gpu_ivf_flat/nlist4096
- algo: faiss_gpu_ivf_flat
  build_param:
    nlist: 8192
  file: index/lastfm-65-angular/faiss_gpu_ivf_flat/nlist8192
  name: faiss_gpu_ivf_flat.nlist8192
  search_params:
  - nprobe: 1
  - nprobe: 5
  - nprobe: 10
  - nprobe: 50
  - nprobe: 100
  - nprobe: 200
  - nprobe: 500
  - nprobe: 1000
  search_result_file: result/lastfm-65-angular/faiss_gpu_ivf_flat/nlist8192
- algo: faiss_gpu_ivf_flat
  build_param:
    nlist: 16384
  file: index/lastfm-65-angular/faiss_gpu_ivf_flat/nlist16384
  name: faiss_gpu_ivf_flat.nlist16384
  search_params:
  - nprobe: 1
  - nprobe: 5
  - nprobe: 10
  - nprobe: 50
  - nprobe: 100
  - nprobe: 200
  - nprobe: 500
  - nprobe: 1000
  - nprobe: 2000
  search_result_file: result/lastfm-65-angular/faiss_gpu_ivf_flat/nlist16384
- algo: faiss_gpu_ivf_pq
  build_param:
    M: 64
    nlist: 1024
    useFloat16: true
    usePrecomputed: true
  file: index/lastfm-65-angular/faiss_gpu_ivf_pq/M64-nlist1024
  name: faiss_gpu_ivf_pq.M64-nlist1024
  search_params:
  - nprobe: 10
  - nprobe: 50
  - nprobe: 100
  - nprobe: 200
  - nprobe: 500
  - nprobe: 1000
  search_result_file: result/lastfm-65-angular/faiss_gpu_ivf_pq/M64-nlist1024
- algo: faiss_gpu_ivf_pq
  build_param:
    M: 64
    nlist: 1024
    useFloat16: true
    usePrecomputed: false
  file: index/lastfm-65-angular/faiss_gpu_ivf_pq/M64-nlist1024.noprecomp
  name: faiss_gpu_ivf_pq.M64-nlist1024.noprecomp
  search_params:
  - nprobe: 10
  - nprobe: 50
  - nprobe: 100
  - nprobe: 200
  - nprobe: 500
  - nprobe: 1000
  search_result_file: result/lastfm-65-angular/faiss_gpu_ivf_pq/M64-nlist1024
- algo: faiss_gpu_ivf_sq
  build_param:
    nlist: 1024
    quantizer_type: fp16
  file: index/lastfm-65-angular/faiss_gpu_ivf_sq/nlist1024-fp16
  name: faiss_gpu_ivf_sq.nlist1024-fp16
  search_params:
  - nprobe: 1
  - nprobe: 5
  - nprobe: 10
  - nprobe: 50
  - nprobe: 100
  - nprobe: 200
  - nprobe: 500
  - nprobe: 1000
  search_result_file: result/lastfm-65-angular/faiss_gpu_ivf_sq/nlist1024-fp16
- algo: faiss_gpu_ivf_sq
  build_param:
    nlist: 2048
    quantizer_type: fp16
  file: index/lastfm-65-angular/faiss_gpu_ivf_sq/nlist2048-fp16
  name: faiss_gpu_ivf_sq.nlist2048-fp16
  search_params:
  - nprobe: 1
  - nprobe: 5
  - nprobe: 10
  - nprobe: 50
  - nprobe: 100
  - nprobe: 200
  - nprobe: 500
  - nprobe: 1000
  search_result_file: result/lastfm-65-angular/faiss_gpu_ivf_sq/nlist2048-fp16
- algo: faiss_gpu_ivf_sq
  build_param:
    nlist: 4096
    quantizer_type: fp16
  file: index/lastfm-65-angular/faiss_gpu_ivf_sq/nlist4096-fp16
  name: faiss_gpu_ivf_sq.nlist4096-fp16
  search_params:
  - nprobe: 1
  - nprobe: 5
  - nprobe: 10
  - nprobe: 50
  - nprobe: 100
  - nprobe: 200
  - nprobe: 500
  - nprobe: 1000
  search_result_file: result/lastfm-65-angular/faiss_gpu_ivf_sq/nlist4096-fp16
- algo: faiss_gpu_ivf_sq
  build_param:
    nlist: 8192
    quantizer_type: fp16
  file: index/lastfm-65-angular/faiss_gpu_ivf_sq/nlist8192-fp16
  name: faiss_gpu_ivf_sq.nlist8192-fp16
  search_params:
  - nprobe: 1
  - nprobe: 5
  - nprobe: 10
  - nprobe: 50
  - nprobe: 100
  - nprobe: 200
  - nprobe: 500
  - nprobe: 1000
  search_result_file: result/lastfm-65-angular/faiss_gpu_ivf_sq/nlist8192-fp16
- algo: faiss_gpu_ivf_sq
  build_param:
    nlist: 16384
    quantizer_type: fp16
  file: index/lastfm-65-angular/faiss_gpu_ivf_sq/nlist16384-fp16
  name: faiss_gpu_ivf_sq.nlist16384-fp16
  search_params:
  - nprobe: 1
  - nprobe: 5
  - nprobe: 10
  - nprobe: 50
  - nprobe: 100
  - nprobe: 200
  - nprobe: 500
  - nprobe: 1000
  - nprobe: 2000
  search_result_file: result/lastfm-65-angular/faiss_gpu_ivf_sq/nlist16384-fp16
- algo: faiss_gpu_ivf_sq
  build_param:
    nlist: 1024
    quantizer_type: int8
  file: index/lastfm-65-angular/faiss_gpu_ivf_sq/nlist1024-int8
  name: faiss_gpu_ivf_sq.nlist1024-int8
  search_params:
  - nprobe: 1
  - nprobe: 5
  - nprobe: 10
  - nprobe: 50
  - nprobe: 100
  - nprobe: 200
  - nprobe: 500
  - nprobe: 1000
  search_result_file: result/lastfm-65-angular/faiss_gpu_ivf_sq/nlist1024-int8
- algo: faiss_gpu_ivf_sq
  build_param:
    nlist: 2048
    quantizer_type: int8
  file: index/lastfm-65-angular/faiss_gpu_ivf_sq/nlist2048-int8
  name: faiss_gpu_ivf_sq.nlist2048-int8
  search_params:
  - nprobe: 1
  - nprobe: 5
  - nprobe: 10
  - nprobe: 50
  - nprobe: 100
  - nprobe: 200
  - nprobe: 500
  - nprobe: 1000
  search_result_file: result/lastfm-65-angular/faiss_gpu_ivf_sq/nlist2048-int8
- algo: faiss_gpu_ivf_sq
  build_param:
    nlist: 4096
    quantizer_type: int8
  file: index/lastfm-65-angular/faiss_gpu_ivf_sq/nlist4096-int8
  name: faiss_gpu_ivf_sq.nlist4096-int8
  search_params:
  - nprobe: 1
  - nprobe: 5
  - nprobe: 10
  - nprobe: 50
  - nprobe: 100
  - nprobe: 200
  - nprobe: 500
  - nprobe: 1000
  search_result_file: result/lastfm-65-angular/faiss_gpu_ivf_sq/nlist4096-int8
- algo: faiss_gpu_ivf_sq
  build_param:
    nlist: 8192
    quantizer_type: int8
  file: index/lastfm-65-angular/faiss_gpu_ivf_sq/nlist8192-int8
  name: faiss_gpu_ivf_sq.nlist8192-int8
  search_params:
  - nprobe: 1
  - nprobe: 5
  - nprobe: 10
  - nprobe: 50
  - nprobe: 100
  - nprobe: 200
  - nprobe: 500
  - nprobe: 1000
  search_result_file: result/lastfm-65-angular/faiss_gpu_ivf_sq/nlist8192-int8
- algo: faiss_gpu_ivf_sq
  build_param:
    nlist: 16384
    quantizer_type: int8
  file: index/lastfm-65-angular/faiss_gpu_ivf_sq/nlist16384-int8
  name: faiss_gpu_ivf_sq.nlist16384-int8
  search_params:
  - nprobe: 1
  - nprobe: 5
  - nprobe: 10
  - nprobe: 50
  - nprobe: 100
  - nprobe: 200
  - nprobe: 500
  - nprobe: 1000
  - nprobe: 2000
  search_result_file: result/lastfm-65-angular/faiss_gpu_ivf_sq/nlist16384-int8
- algo: faiss_gpu_flat
  build_param: {}
  file: index/lastfm-65-angular/faiss_gpu_flat/flat
  name: faiss_gpu_flat
  search_params:
  - {}
  search_result_file: result/lastfm-65-angular/faiss_gpu_flat/flat
- algo: raft_ivf_pq
  build_param:
    niter: 25
    nlist: 1024
    pq_dim: 128
    ratio: 1
  file: index/lastfm-65-angular/raft_ivf_pq/dimpq128-cluster1024
  name: raft_ivf_pq.dimpq128-cluster1024
  search_params:
  - internalDistanceDtype: half
    k: 10
    numProbes: 10
    smemLutDtype: half
  - internalDistanceDtype: half
    k: 10
    numProbes: 50
    smemLutDtype: half
  - internalDistanceDtype: half
    k: 10
    numProbes: 100
    smemLutDtype: half
  - internalDistanceDtype: half
    k: 10
    numProbes: 200
    smemLutDtype: half
  - internalDistanceDtype: half
    k: 10
    numProbes: 500
    smemLutDtype: half
  - internalDistanceDtype: half
    k: 10
    numProbes: 1024
    smemLutDtype: half
  search_result_file: result/lastfm-65-angular/raft_ivf_pq/dimpq128-cluster1024
- algo: raft_ivf_pq
  build_param:
    niter: 25
    nlist: 1024
    pq_dim: 128
    ratio: 1
  file: index/lastfm-65-angular/raft_ivf_pq/dimpq128-cluster1024-float-float
  name: raft_ivf_pq.dimpq128-cluster1024-float-float
  search_params:
  - internalDistanceDtype: float
    k: 10
    numProbes: 1
    smemLutDtype: float
  - internalDistanceDtype: float
    k: 10
    numProbes: 1
    smemLutDtype: float
  - internalDistanceDtype: float
    k: 10
    numProbes: 5
    smemLutDtype: float
  - internalDistanceDtype: float
    k: 10
    numProbes: 10
    smemLutDtype: float
  - internalDistanceDtype: float
    k: 10
    numProbes: 50
    smemLutDtype: float
  - internalDistanceDtype: float
    k: 10
    numProbes: 100
    smemLutDtype: float
  - internalDistanceDtype: float
    k: 10
    numProbes: 200
    smemLutDtype: float
  - internalDistanceDtype: float
    k: 10
    numProbes: 500
    smemLutDtype: float
  - internalDistanceDtype: float
    k: 10
    numProbes: 1024
    smemLutDtype: float
  search_result_file: result/lastfm-65-angular/raft_ivf_pq/dimpq128-cluster1024-float-float
- algo: raft_ivf_pq
  build_param:
    niter: 25
    nlist: 1024
    pq_dim: 128
    ratio: 1
  file: index/lastfm-65-angular/raft_ivf_pq/dimpq128-cluster1024-float-half
  name: raft_ivf_pq.dimpq128-cluster1024-float-half
  search_params:
  - internalDistanceDtype: float
    k: 10
    numProbes: 10
    smemLutDtype: half
  - internalDistanceDtype: float
    k: 10
    numProbes: 50
    smemLutDtype: half
  - internalDistanceDtype: float
    k: 10
    numProbes: 100
    smemLutDtype: half
  - internalDistanceDtype: float
    k: 10
    numProbes: 200
    smemLutDtype: half
  - internalDistanceDtype: float
    k: 10
    numProbes: 500
    smemLutDtype: half
  - internalDistanceDtype: float
    k: 10
    numProbes: 1024
    smemLutDtype: half
  search_result_file: result/lastfm-65-angular/raft_ivf_pq/dimpq128-cluster1024-float-half
- algo: raft_ivf_pq
  build_param:
    niter: 25
    nlist: 1024
    pq_dim: 128
    ratio: 1
  file: index/lastfm-65-angular/raft_ivf_pq/dimpq128-cluster1024-float-fp8
  name: raft_ivf_pq.dimpq128-cluster1024-float-fp8
  search_params:
  - internalDistanceDtype: float
    k: 10
    numProbes: 10
    smemLutDtype: fp8
  - internalDistanceDtype: float
    k: 10
    numProbes: 50
    smemLutDtype: fp8
  - internalDistanceDtype: float
    k: 10
    numProbes: 100
    smemLutDtype: fp8
  - internalDistanceDtype: float
    k: 10
    numProbes: 200
    smemLutDtype: fp8
  - internalDistanceDtype: float
    k: 10
    numProbes: 500
    smemLutDtype: fp8
  - internalDistanceDtype: float
    k: 10
    numProbes: 1024
    smemLutDtype: fp8
  search_result_file: result/lastfm-65-angular/raft_ivf_pq/dimpq128-cluster1024-float-fp8
- algo: raft_ivf_pq
  build_param:
    niter: 25
    nlist: 1024
    pq_dim: 64
    ratio: 1
  file: index/lastfm-65-angular/raft_ivf_pq/dimpq64-cluster1024-float-fp8
  name: raft_ivf_pq.dimpq64-cluster1024-float-fp8
  search_params:
  - internalDistanceDtype: float
    k: 10
    numProbes: 10
    smemLutDtype: fp8
  - internalDistanceDtype: float
    k: 10
    numProbes: 50
    smemLutDtype: fp8
  - internalDistanceDtype: float
    k: 10
    numProbes: 100
    smemLutDtype: fp8
  - internalDistanceDtype: float
    k: 10
    numProbes: 200
    smemLutDtype: fp8
  - internalDistanceDtype: float
    k: 10
    numProbes: 500
    smemLutDtype: fp8
  - internalDistanceDtype: float
    k: 10
    numProbes: 1024
    smemLutDtype: fp8
  search_result_file: result/lastfm-65-angular/raft_ivf_pq/dimpq64-cluster1024-float-fp8
- algo: raft_ivf_pq
  build_param:
    niter: 25
    nlist: 1024
    pq_dim: 64
    ratio: 1
  file: index/lastfm-65-angular/raft_ivf_pq/dimpq64-cluster1024-float-half
  name: raft_ivf_pq.dimpq64-cluster1024-float-half
  search_params:
  - internalDistanceDtype: float
    k: 10
    numProbes: 10
    smemLutDtype: half
  - internalDistanceDtype: float
    k: 10
    numProbes: 50
    smemLutDtype: half
  - internalDistanceDtype: float
    k: 10
    numProbes: 100
    smemLutDtype: half
  - internalDistanceDtype: float
    k: 10
    numProbes: 200
    smemLutDtype: half
  - internalDistanceDtype: float
    k: 10
    numProbes: 500
    smemLutDtype: half
  - internalDistanceDtype: float
    k: 10
    numProbes: 1024
    smemLutDtype: half
  search_result_file: result/lastfm-65-angular/raft_ivf_pq/dimpq64-cluster1024-float-half
- algo: raft_ivf_pq
  build_param:
    niter: 25
    nlist: 1024
    pq_dim: 32
    ratio: 1
  file: index/lastfm-65-angular/raft_ivf_pq/dimpq32-cluster1024-float-fp8
  name: raft_ivf_pq.dimpq32-cluster1024-float-fp8
  search_params:
  - internalDistanceDtype: float
    k: 10
    numProbes: 10
    smemLutDtype: fp8
  - internalDistanceDtype: float
    k: 10
    numProbes: 50
    smemLutDtype: fp8
  - internalDistanceDtype: float
    k: 10
    numProbes: 100
    smemLutDtype: fp8
  - internalDistanceDtype: float
    k: 10
    numProbes: 200
    smemLutDtype: fp8
  - internalDistanceDtype: float
    k: 10
    numProbes: 500
    smemLutDtype: fp8
  - internalDistanceDtype: float
    k: 10
    numProbes: 1024
    smemLutDtype: fp8
  search_result_file: result/lastfm-65-angular/raft_ivf_pq/dimpq32-cluster1024-float-fp8
- algo: raft_ivf_pq
  build_param:
    niter: 25
    nlist: 1024
    pq_dim: 16
    ratio: 1
  file: index/lastfm-65-angular/raft_ivf_pq/dimpq16-cluster1024-float-fp8
  name: raft_ivf_pq.dimpq16-cluster1024-float-fp8
  search_params:
  - internalDistanceDtype: float
    k: 10
    numProbes: 10
    smemLutDtype: fp8
  - internalDistanceDtype: float
    k: 10
    numProbes: 50
    smemLutDtype: fp8
  - internalDistanceDtype: float
    k: 10
    numProbes: 100
    smemLutDtype: fp8
  - internalDistanceDtype: float
    k: 10
    numProbes: 200
    smemLutDtype: fp8
  - internalDistanceDtype: float
    k: 10
    numProbes: 500
    smemLutDtype: fp8
  - internalDistanceDtype: float
    k: 10
    numProbes: 1024
    smemLutDtype: fp8
  search_result_file: result/lastfm-65-angular/raft_ivf_pq/dimpq16-cluster1024-float-fp8
- algo: raft_ivf_pq
  build_param:
    niter: 25
    nlist: 1024
    pq_dim: 128
    ratio: 1
  file: index/lastfm-65-angular/raft_ivf_pq/dimpq128-cluster1024-half-float
  name: raft_ivf_pq.dimpq128-cluster1024-half-float
  search_params:
  - internalDistanceDtype: half
    k: 10
    numProbes: 10
    smemLutDtype: float
  - internalDistanceDtype: half
    k: 10
    numProbes: 50
    smemLutDtype: float
  - internalDistanceDtype: half
    k: 10
    numProbes: 100
    smemLutDtype: float
  - internalDistanceDtype: half
    k: 10
    numProbes: 200
    smemLutDtype: float
  - internalDistanceDtype: half
    k: 10
    numProbes: 500
    smemLutDtype: float
  - internalDistanceDtype: half
    k: 10
    numProbes: 1024
    smemLutDtype: float
  search_result_file: result/lastfm-65-angular/raft_ivf_pq/dimpq128-cluster1024-half-float
- algo: raft_ivf_pq
  build_param:
    niter: 25
    nlist: 1024
    pq_dim: 512
    ratio: 1
  file: index/lastfm-65-angular/raft_ivf_pq/dimpq512-cluster1024-float-float
  name: raft_ivf_pq.dimpq512-cluster1024-float-float
  search_params:
  - internalDistanceDtype: float
    k: 10
    numProbes: 10
    smemLutDtype: float
  - internalDistanceDtype: float
    k: 10
    numProbes: 50
    smemLutDtype: float
  - internalDistanceDtype: float
    k: 10
    numProbes: 100
    smemLutDtype: float
  - internalDistanceDtype: float
    k: 10
    numProbes: 200
    smemLutDtype: float
  - internalDistanceDtype: float
    k: 10
    numProbes: 500
    smemLutDtype: float
  - internalDistanceDtype: float
    k: 10
    numProbes: 1024
    smemLutDtype: float
  search_result_file: result/lastfm-65-angular/raft_ivf_pq/dimpq512-cluster1024-float-float
- algo: raft_ivf_flat
  build_param:
    niter: 25
    nlist: 1024
    ratio: 1
  file: index/lastfm-65-angular/raft_ivf_flat/nlist1024
  name: raft_ivf_flat.nlist1024
  search_params:
  - nprobe: 1
  - nprobe: 5
  - nprobe: 10
  - nprobe: 50
  - nprobe: 100
  - nprobe: 200
  - nprobe: 500
  - nprobe: 1000
  search_result_file: result/lastfm-65-angular/raft_ivf_flat/nlist1024
- algo: raft_ivf_flat
  build_param:
    niter: 20
    nlist: 16384
    ratio: 2
  file: index/lastfm-65-angular/raft_ivf_flat/nlist16384
  name: raft_ivf_flat.nlist16384
  search_params:
  - nprobe: 1
  - nprobe: 5
  - nprobe: 10
  - nprobe: 50
  - nprobe: 100
  - nprobe: 200
  - nprobe: 500
  - nprobe: 1000
  - nprobe: 2000
  search_result_file: result/lastfm-65-angular/raft_ivf_flat/nlist16384
- algo: raft_cagra
  build_param:
    graph_degree: 32
  file: index/lastfm-65-angular/raft_cagra/dim32
  name: raft_cagra.dim32
  search_params:
  - itopk: 32
  - itopk: 64
  - itopk: 128
  search_result_file: result/lastfm-65-angular/raft_cagra/dim32
- algo: raft_cagra
  build_param:
    graph_degree: 64
  file: index/lastfm-65-angular/raft_cagra/dim64
  name: raft_cagra.dim64
  search_params:
  - itopk: 32
  - itopk: 64
  - itopk: 128
  search_result_file: result/lastfm-65-angular/raft_cagra/dim64
search_basic_param:
  batch_size: 5000
  k: 10
  run_count: 3
