dataset:
  base_file: sift-128-euclidean/base.fbin
  distance: euclidean
  groundtruth_neighbors_file: sift-128-euclidean/groundtruth.neighbors.ibin
  name: sift-128-euclidean
  query_file: sift-128-euclidean/query.fbin
index:
- algo: hnswlib
  build_param:
    M: 12
    efConstruction: 500
    numThreads: 32
  file: sift-128-euclidean/hnswlib/M12
  name: hnswlib.M12
  search_params:
  - ef: 10
  - ef: 20
  - ef: 40
  - ef: 60
  - ef: 80
  - ef: 120
  - ef: 200
  - ef: 400
  - ef: 600
  - ef: 800
- algo: hnswlib
  build_param:
    M: 16
    efConstruction: 500
    numThreads: 32
  file: sift-128-euclidean/hnswlib/M16
  name: hnswlib.M16
  search_params:
  - ef: 10
  - ef: 20
  - ef: 40
  - ef: 60
  - ef: 80
  - ef: 120
  - ef: 200
  - ef: 400
  - ef: 600
  - ef: 800
- algo: hnswlib
  build_param:
    M: 24
    efConstruction: 500
    numThreads: 32
  file: sift-128-euclidean/hnswlib/M24
  name: hnswlib.M24
  search_params:
  - ef: 10
  - ef: 20
  - ef: 40
  - ef: 60
  - ef: 80
  - ef: 120
  - ef: 200
  - ef: 400
  - ef: 600
  - ef: 800
- algo: hnswlib
  build_param:
    M: 36
    efConstruction: 500
    numThreads: 32
  file: sift-128-euclidean/hnswlib/M36
  name: hnswlib.M36
  search_params:
  - ef: 10
  - ef: 20
  - ef: 40
  - ef: 60
  - ef: 80
  - ef: 120
  - ef: 200
  - ef: 400
  - ef: 600
  - ef: 800
- algo: raft_bfknn
  build_param: {}
  file: sift-128-euclidean/raft_bfknn/bfknn
  name: raft_bfknn
  search_params:
  - probe: 1
- algo: faiss_gpu_ivf_flat
  build_param:
    nlist: 1024
  file: sift-128-euclidean/faiss_gpu_ivf_flat/nlist1024
  name: faiss_gpu_ivf_flat.nlist1024
  search_params:
  - nprobe: 1
  - nprobe: 5
  - nprobe: 10
  - nprobe: 50
  - nprobe: 100
  - nprobe: 200
  - nprobe: 500
  - nprobe: 1000
- algo: faiss_gpu_ivf_flat
  build_param:
    nlist: 2048
  file: sift-128-euclidean/faiss_gpu_ivf_flat/nlist2048
  name: faiss_gpu_ivf_flat.nlist2048
  search_params:
  - nprobe: 1
  - nprobe: 5
  - nprobe: 10
  - nprobe: 50
  - nprobe: 100
  - nprobe: 200
  - nprobe: 500
  - nprobe: 1000
- algo: faiss_gpu_ivf_flat
  build_param:
    nlist: 4096
  file: sift-128-euclidean/faiss_gpu_ivf_flat/nlist4096
  name: faiss_gpu_ivf_flat.nlist4096
  search_params:
  - nprobe: 1
  - nprobe: 5
  - nprobe: 10
  - nprobe: 50
  - nprobe: 100
  - nprobe: 200
  - nprobe: 500
  - nprobe: 1000
- algo: faiss_gpu_ivf_flat
  build_param:
    nlist: 8192
  file: sift-128-euclidean/faiss_gpu_ivf_flat/nlist8192
  name: faiss_gpu_ivf_flat.nlist8192
  search_params:
  - nprobe: 1
  - nprobe: 5
  - nprobe: 10
  - nprobe: 50
  - nprobe: 100
  - nprobe: 200
  - nprobe: 500
  - nprobe: 1000
- algo: faiss_gpu_ivf_flat
  build_param:
    nlist: 16384
  file: sift-128-euclidean/faiss_gpu_ivf_flat/nlist16384
  name: faiss_gpu_ivf_flat.nlist16384
  search_params:
  - nprobe: 1
  - nprobe: 5
  - nprobe: 10
  - nprobe: 50
  - nprobe: 100
  - nprobe: 200
  - nprobe: 500
  - nprobe: 1000
  - nprobe: 2000
- algo: faiss_gpu_ivf_pq
  build_param:
    M: 64
    nlist: 1024
    useFloat16: true
    usePrecomputed: true
  file: sift-128-euclidean/faiss_gpu_ivf_pq/M64-nlist1024
  name: faiss_gpu_ivf_pq.M64-nlist1024
  search_params:
  - nprobe: 10
  - nprobe: 50
  - nprobe: 100
  - nprobe: 200
  - nprobe: 500
  - nprobe: 1000
- algo: faiss_gpu_ivf_pq
  build_param:
    M: 64
    nlist: 1024
    useFloat16: true
    usePrecomputed: false
  file: sift-128-euclidean/faiss_gpu_ivf_pq/M64-nlist1024.noprecomp
  name: faiss_gpu_ivf_pq.M64-nlist1024.noprecomp
  search_params:
  - nprobe: 10
  - nprobe: 50
  - nprobe: 100
  - nprobe: 200
  - nprobe: 500
  - nprobe: 1000
- algo: faiss_gpu_ivf_sq
  build_param:
    nlist: 1024
    quantizer_type: fp16
  file: sift-128-euclidean/faiss_gpu_ivf_sq/nlist1024-fp16
  name: faiss_gpu_ivf_sq.nlist1024-fp16
  search_params:
  - nprobe: 1
  - nprobe: 5
  - nprobe: 10
  - nprobe: 50
  - nprobe: 100
  - nprobe: 200
  - nprobe: 500
  - nprobe: 1000
- algo: faiss_gpu_ivf_sq
  build_param:
    nlist: 2048
    quantizer_type: fp16
  file: sift-128-euclidean/faiss_gpu_ivf_sq/nlist2048-fp16
  name: faiss_gpu_ivf_sq.nlist2048-fp16
  search_params:
  - nprobe: 1
  - nprobe: 5
  - nprobe: 10
  - nprobe: 50
  - nprobe: 100
  - nprobe: 200
  - nprobe: 500
  - nprobe: 1000
- algo: faiss_gpu_ivf_sq
  build_param:
    nlist: 4096
    quantizer_type: fp16
  file: sift-128-euclidean/faiss_gpu_ivf_sq/nlist4096-fp16
  name: faiss_gpu_ivf_sq.nlist4096-fp16
  search_params:
  - nprobe: 1
  - nprobe: 5
  - nprobe: 10
  - nprobe: 50
  - nprobe: 100
  - nprobe: 200
  - nprobe: 500
  - nprobe: 1000
- algo: faiss_gpu_ivf_sq
  build_param:
    nlist: 8192
    quantizer_type: fp16
  file: sift-128-euclidean/faiss_gpu_ivf_sq/nlist8192-fp16
  name: faiss_gpu_ivf_sq.nlist8192-fp16
  search_params:
  - nprobe: 1
  - nprobe: 5
  - nprobe: 10
  - nprobe: 50
  - nprobe: 100
  - nprobe: 200
  - nprobe: 500
  - nprobe: 1000
- algo: faiss_gpu_ivf_sq
  build_param:
    nlist: 16384
    quantizer_type: fp16
  file: sift-128-euclidean/faiss_gpu_ivf_sq/nlist16384-fp16
  name: faiss_gpu_ivf_sq.nlist16384-fp16
  search_params:
  - nprobe: 1
  - nprobe: 5
  - nprobe: 10
  - nprobe: 50
  - nprobe: 100
  - nprobe: 200
  - nprobe: 500
  - nprobe: 1000
  - nprobe: 2000
- algo: faiss_gpu_ivf_sq
  build_param:
    nlist: 1024
    quantizer_type: int8
  file: sift-128-euclidean/faiss_gpu_ivf_sq/nlist1024-int8
  name: faiss_gpu_ivf_sq.nlist1024-int8
  search_params:
  - nprobe: 1
  - nprobe: 5
  - nprobe: 10
  - nprobe: 50
  - nprobe: 100
  - nprobe: 200
  - nprobe: 500
  - nprobe: 1000
- algo: faiss_gpu_ivf_sq
  build_param:
    nlist: 2048
    quantizer_type: int8
  file: sift-128-euclidean/faiss_gpu_ivf_sq/nlist2048-int8
  name: faiss_gpu_ivf_sq.nlist2048-int8
  search_params:
  - nprobe: 1
  - nprobe: 5
  - nprobe: 10
  - nprobe: 50
  - nprobe: 100
  - nprobe: 200
  - nprobe: 500
  - nprobe: 1000
- algo: faiss_gpu_ivf_sq
  build_param:
    nlist: 4096
    quantizer_type: int8
  file: sift-128-euclidean/faiss_gpu_ivf_sq/nlist4096-int8
  name: faiss_gpu_ivf_sq.nlist4096-int8
  search_params:
  - nprobe: 1
  - nprobe: 5
  - nprobe: 10
  - nprobe: 50
  - nprobe: 100
  - nprobe: 200
  - nprobe: 500
  - nprobe: 1000
- algo: faiss_gpu_ivf_sq
  build_param:
    nlist: 8192
    quantizer_type: int8
  file: sift-128-euclidean/faiss_gpu_ivf_sq/nlist8192-int8
  name: faiss_gpu_ivf_sq.nlist8192-int8
  search_params:
  - nprobe: 1
  - nprobe: 5
  - nprobe: 10
  - nprobe: 50
  - nprobe: 100
  - nprobe: 200
  - nprobe: 500
  - nprobe: 1000
- algo: faiss_gpu_ivf_sq
  build_param:
    nlist: 16384
    quantizer_type: int8
  file: sift-128-euclidean/faiss_gpu_ivf_sq/nlist16384-int8
  name: faiss_gpu_ivf_sq.nlist16384-int8
  search_params:
  - nprobe: 1
  - nprobe: 5
  - nprobe: 10
  - nprobe: 50
  - nprobe: 100
  - nprobe: 200
  - nprobe: 500
  - nprobe: 1000
  - nprobe: 2000
- algo: faiss_gpu_flat
  build_param: {}
  file: sift-128-euclidean/faiss_gpu_flat/flat
  name: faiss_gpu_flat
  search_params:
  - {}
- algo: raft_ivf_pq
  build_param:
    niter: 25
    nlist: 1000
    pq_bits: 8
    pq_dim: 64
    ratio: 1
  file: sift-128-euclidean/raft_ivf_pq/dimpq64-bitpq8-cluster1K
  name: raft_ivf_pq.dimpq64-bitpq8-cluster1K
  search_params:
  - internalDistanceDtype: float
    nprobe: 20
    smemLutDtype: float
  - internalDistanceDtype: float
    nprobe: 30
    smemLutDtype: float
  - internalDistanceDtype: float
    nprobe: 40
    smemLutDtype: float
  - internalDistanceDtype: float
    nprobe: 50
    smemLutDtype: float
  - internalDistanceDtype: float
    nprobe: 100
    smemLutDtype: float
  - internalDistanceDtype: float
    nprobe: 200
    smemLutDtype: float
  - internalDistanceDtype: float
    nprobe: 500
    smemLutDtype: float
  - internalDistanceDtype: float
    nprobe: 1000
    smemLutDtype: float
  - internalDistanceDtype: float
    nprobe: 20
    smemLutDtype: fp8
  - internalDistanceDtype: float
    nprobe: 30
    smemLutDtype: fp8
  - internalDistanceDtype: float
    nprobe: 40
    smemLutDtype: fp8
  - internalDistanceDtype: float
    nprobe: 50
    smemLutDtype: fp8
  - internalDistanceDtype: float
    nprobe: 100
    smemLutDtype: fp8
  - internalDistanceDtype: float
    nprobe: 200
    smemLutDtype: fp8
  - internalDistanceDtype: float
    nprobe: 500
    smemLutDtype: fp8
  - internalDistanceDtype: float
    nprobe: 1000
    smemLutDtype: fp8
  - internalDistanceDtype: half
    nprobe: 20
    smemLutDtype: half
  - internalDistanceDtype: half
    nprobe: 30
    smemLutDtype: half
  - internalDistanceDtype: half
    nprobe: 40
    smemLutDtype: half
  - internalDistanceDtype: half
    nprobe: 50
    smemLutDtype: half
  - internalDistanceDtype: half
    nprobe: 100
    smemLutDtype: half
  - internalDistanceDtype: half
    nprobe: 200
    smemLutDtype: half
  - internalDistanceDtype: half
    nprobe: 500
    smemLutDtype: half
  - internalDistanceDtype: half
    nprobe: 1000
    smemLutDtype: half
- algo: raft_ivf_pq
  build_param:
    niter: 25
    nlist: 1000
    pq_bits: 6
    pq_dim: 128
    ratio: 1
  file: sift-128-euclidean/raft_ivf_pq/dimpq128-bitpq6-cluster1K
  name: raft_ivf_pq.dimpq128-bitpq6-cluster1K
  search_params:
  - internalDistanceDtype: float
    nprobe: 20
    smemLutDtype: float
  - internalDistanceDtype: float
    nprobe: 30
    smemLutDtype: float
  - internalDistanceDtype: float
    nprobe: 40
    smemLutDtype: float
  - internalDistanceDtype: float
    nprobe: 50
    smemLutDtype: float
  - internalDistanceDtype: float
    nprobe: 100
    smemLutDtype: float
  - internalDistanceDtype: float
    nprobe: 200
    smemLutDtype: float
  - internalDistanceDtype: float
    nprobe: 500
    smemLutDtype: float
  - internalDistanceDtype: float
    nprobe: 1000
    smemLutDtype: float
  - internalDistanceDtype: float
    nprobe: 20
    smemLutDtype: fp8
  - internalDistanceDtype: float
    nprobe: 30
    smemLutDtype: fp8
  - internalDistanceDtype: float
    nprobe: 40
    smemLutDtype: fp8
  - internalDistanceDtype: float
    nprobe: 50
    smemLutDtype: fp8
  - internalDistanceDtype: float
    nprobe: 100
    smemLutDtype: fp8
  - internalDistanceDtype: float
    nprobe: 200
    smemLutDtype: fp8
  - internalDistanceDtype: float
    nprobe: 500
    smemLutDtype: fp8
  - internalDistanceDtype: float
    nprobe: 1000
    smemLutDtype: fp8
  - internalDistanceDtype: half
    nprobe: 20
    smemLutDtype: half
  - internalDistanceDtype: half
    nprobe: 30
    smemLutDtype: half
  - internalDistanceDtype: half
    nprobe: 40
    smemLutDtype: half
  - internalDistanceDtype: half
    nprobe: 50
    smemLutDtype: half
  - internalDistanceDtype: half
    nprobe: 100
    smemLutDtype: half
  - internalDistanceDtype: half
    nprobe: 200
    smemLutDtype: half
  - internalDistanceDtype: half
    nprobe: 500
    smemLutDtype: half
  - internalDistanceDtype: half
    nprobe: 1000
    smemLutDtype: half
- algo: raft_ivf_flat
  build_param:
    niter: 25
    nlist: 1024
    ratio: 1
  file: sift-128-euclidean/raft_ivf_flat/nlist1024
  name: raft_ivf_flat.nlist1024
  search_params:
  - nprobe: 1
  - nprobe: 5
  - nprobe: 10
  - nprobe: 50
  - nprobe: 100
  - nprobe: 200
  - nprobe: 500
  - nprobe: 1000
- algo: raft_ivf_flat
  build_param:
    niter: 20
    nlist: 16384
    ratio: 2
  file: sift-128-euclidean/raft_ivf_flat/nlist16384
  name: raft_ivf_flat.nlist16384
  search_params:
  - nprobe: 1
  - nprobe: 5
  - nprobe: 10
  - nprobe: 50
  - nprobe: 100
  - nprobe: 200
  - nprobe: 500
  - nprobe: 1000
  - nprobe: 2000
- algo: raft_cagra
  build_param:
    graph_degree: 32
  file: sift-128-euclidean/raft_cagra/dim32
  name: raft_cagra.dim32
  search_params:
  - itopk: 32
  - itopk: 64
  - itopk: 128
- algo: raft_cagra
  build_param:
    graph_degree: 64
  file: sift-128-euclidean/raft_cagra/dim64
  name: raft_cagra.dim64
  search_params:
  - itopk: 32
  - itopk: 64
  - itopk: 128
search_basic_param:
  batch_size: 5000
  k: 10
