/*
 * SPDX-FileCopyrightText: Copyright (c) 2024, NVIDIA CORPORATION.
 * SPDX-License-Identifier: Apache-2.0
 */

/*
 * NOTE: this file is generated by generate_ivf_pq.py
 *
 * Make changes there and run in this directory:
 *
 * > python generate_ivf_pq.py
 *
 */

#include <cuvs/neighbors/ivf_pq.hpp>

#include "../ivf_pq_search.cuh"

namespace cuvs::neighbors::ivf_pq {

#define CUVS_INST_IVF_PQ_SEARCH(T, IdxT)                                        \
  void search(raft::resources const& handle,                                    \
              const cuvs::neighbors::ivf_pq::search_params& params,             \
              const cuvs::neighbors::ivf_pq::index<IdxT>& index,                \
              raft::device_matrix_view<const T, IdxT, raft::row_major> queries, \
              raft::device_matrix_view<IdxT, IdxT, raft::row_major> neighbors,  \
              raft::device_matrix_view<float, IdxT, raft::row_major> distances, \
              const cuvs::neighbors::filtering::base_filter& sample_filter_ref) \
  {                                                                             \
    cuvs::neighbors::ivf_pq::detail::search(                                    \
      handle, params, index, queries, neighbors, distances, sample_filter_ref); \
  }
CUVS_INST_IVF_PQ_SEARCH(half, int64_t);

#undef CUVS_INST_IVF_PQ_SEARCH

}  // namespace cuvs::neighbors::ivf_pq
