/*
 * SPDX-FileCopyrightText: Copyright (c) 2024-2025, NVIDIA CORPORATION.
 * SPDX-License-Identifier: Apache-2.0
 */

/*
 * NOTE: this file is generated by generate_ivf_pq_compute_similarity.py
 * Make changes there and run in this directory:
 * > python generate_ivf_pq_compute_similarity.py
 */

#include "../../sample_filter.cuh"
#include "../ivf_pq_compute_similarity_impl.cuh"
#include "../ivf_pq_fp_8bit.cuh"

#define instantiate_cuvs_neighbors_ivf_pq_detail_compute_similarity_select(OutT, LutT)  \
  template auto cuvs::neighbors::ivf_pq::detail::compute_similarity_select<OutT, LutT>( \
    const cudaDeviceProp& dev_props,                                                    \
    bool manage_local_topk,                                                             \
    int locality_hint,                                                                  \
    double preferred_shmem_carveout,                                                    \
    uint32_t pq_bits,                                                                   \
    uint32_t pq_dim,                                                                    \
    uint32_t precomp_data_count,                                                        \
    uint32_t n_queries,                                                                 \
    uint32_t n_probes,                                                                  \
    uint32_t topk) -> cuvs::neighbors::ivf_pq::detail::selected<OutT, LutT>;            \
                                                                                        \
  template void cuvs::neighbors::ivf_pq::detail::compute_similarity_run<OutT, LutT>(    \
    cuvs::neighbors::ivf_pq::detail::selected<OutT, LutT> s,                            \
    rmm::cuda_stream_view stream,                                                       \
    uint32_t dim,                                                                       \
    uint32_t n_probes,                                                                  \
    uint32_t pq_dim,                                                                    \
    uint32_t n_queries,                                                                 \
    uint32_t queries_offset,                                                            \
    cuvs::distance::DistanceType metric,                                                \
    cuvs::neighbors::ivf_pq::codebook_gen codebook_kind,                                \
    uint32_t topk,                                                                      \
    uint32_t max_samples,                                                               \
    const float* cluster_centers,                                                       \
    const float* pq_centers,                                                            \
    const uint8_t* const* pq_dataset,                                                   \
    const uint32_t* cluster_labels,                                                     \
    const uint32_t* _chunk_indices,                                                     \
    const float* queries,                                                               \
    const uint32_t* index_list,                                                         \
    float* query_kths,                                                                  \
    const cuvs::neighbors::filtering::base_filter& sample_filter,                       \
    LutT* lut_scores,                                                                   \
    OutT* _out_scores,                                                                  \
    uint32_t* _out_indices);

#define COMMA ,
instantiate_cuvs_neighbors_ivf_pq_detail_compute_similarity_select(
  float, cuvs::neighbors::ivf_pq::detail::fp_8bit<5u COMMA false>);
