# SPDX-FileCopyrightText: Copyright (c) 2025-2026, NVIDIA CORPORATION.
# SPDX-License-Identifier: Apache-2.0

import datetime

header = f"""/*
 * SPDX-FileCopyrightText: Copyright (c) 2024-{datetime.datetime.today().year}, NVIDIA CORPORATION.
 * SPDX-License-Identifier: Apache-2.0
 */

/*
 * NOTE: this file is generated by registers_00_generate.py
 *
 * Make changes there and run in this directory:
 *
 * > python registers_00_generate.py
 *
 */

#include <cstdint> // int64_t
#include <cuvs/neighbors/ball_cover.hpp>
#include "../../registers.cuh"

"""


macro_pass_one = """
#define instantiate_cuvs_neighbors_detail_rbc_low_dim_pass_one(                            \\
  Mvalue_idx, Mvalue_t)                          \\
  template void                                                                              \\
  cuvs::neighbors::ball_cover::detail::rbc_low_dim_pass_one<Mvalue_idx, Mvalue_t>( \\
    raft::resources const& handle,                                                           \\
    const cuvs::neighbors::ball_cover::index<Mvalue_idx, Mvalue_t>& index,              \\
    const Mvalue_t* query,                                                                   \\
    const int64_t n_query_rows,                                                           \\
    const int64_t k,                                                                            \\
    const Mvalue_idx* R_knn_inds,                                                            \\
    const Mvalue_t* R_knn_dists,                                                             \\
    Mvalue_idx* inds,                                                                        \\
    Mvalue_t* dists,                                                                         \\
    float weight,                                                                            \\
    int dims);

"""

macro_pass_two = """
#define instantiate_cuvs_neighbors_detail_rbc_low_dim_pass_two(                            \\
  Mvalue_idx, Mvalue_t)                          \\
  template void                                                                              \\
  cuvs::neighbors::ball_cover::detail::rbc_low_dim_pass_two<Mvalue_idx, Mvalue_t>( \\
    raft::resources const& handle,                                                           \\
    const cuvs::neighbors::ball_cover::index<Mvalue_idx, Mvalue_t>& index,              \\
    const Mvalue_t* query,                                                                   \\
    const int64_t n_query_rows,                                                           \\
    const int64_t k,                                                                            \\
    const Mvalue_idx* R_knn_inds,                                                            \\
    const Mvalue_t* R_knn_dists,                                                             \\
    Mvalue_idx* inds,                                                                        \\
    Mvalue_t* dists,                                                                         \\
    float weight,                                                                            \\
    int dims);

"""

macro_pass_eps = """
#define instantiate_cuvs_neighbors_detail_rbc_eps_pass(                                  \\
  Mvalue_idx, Mvalue_t, Mdist_func)                               \\
  template void                                                                            \\
  cuvs::neighbors::ball_cover::detail::rbc_eps_pass<Mvalue_idx, Mvalue_t>( \\
    raft::resources const& handle,                                                         \\
    const cuvs::neighbors::ball_cover::index<Mvalue_idx, Mvalue_t>& index,            \\
    const Mvalue_t* query,                                                                 \\
    const int64_t n_query_rows,                                                         \\
    Mvalue_t eps,                                                                          \\
    const Mvalue_t* R_dists,                                                               \\
    Mdist_func<Mvalue_t, int64_t>& dfunc,                                               \\
    bool* adj,                                                                             \\
    Mvalue_idx* vd);                                                                       \\
                                                                                           \\
  template void                                                                            \\
  cuvs::neighbors::ball_cover::detail::rbc_eps_pass<Mvalue_idx, Mvalue_t>( \\
    raft::resources const& handle,                                                         \\
    const cuvs::neighbors::ball_cover::index<Mvalue_idx, Mvalue_t>& index,            \\
    const Mvalue_t* query,                                                                 \\
    const int64_t n_query_rows,                                                         \\
    Mvalue_t eps,                                                                          \\
    int64_t* max_k,                                                                     \\
    const Mvalue_t* R_dists,                                                               \\
    Mdist_func<Mvalue_t, int64_t>& dfunc,                                               \\
    Mvalue_idx* adj_ia,                                                                    \\
    Mvalue_idx* adj_ja,                                                                    \\
    Mvalue_idx* vd,                                                                        \\
    Mvalue_t* dists)

"""

euclideanSq = "cuvs::neighbors::ball_cover::detail::EuclideanSqFunc"

types = dict(
    int64_float=("std::int64_t", "float"),
)

path = "registers_pass_one.cu"
with open(path, "w") as f:
    f.write(header)
    f.write(macro_pass_one)
    for type_path, (int_t, data_t) in types.items():
        f.write("instantiate_cuvs_neighbors_detail_rbc_low_dim_pass_one(\n")
        f.write(f"  {int_t}, {data_t});\n")
    f.write("#undef instantiate_cuvs_neighbors_detail_rbc_low_dim_pass_one\n")
print(f"src/neighbors/ball_cover/detail/ball_cover/{path}")

path = "registers_pass_two.cu"
with open(path, "w") as f:
    f.write(header)
    f.write(macro_pass_two)
    for type_path, (int_t, data_t) in types.items():
        f.write("instantiate_cuvs_neighbors_detail_rbc_low_dim_pass_two(\n")
        f.write(f"  {int_t}, {data_t});\n")
    f.write("#undef instantiate_cuvs_neighbors_detail_rbc_low_dim_pass_two\n")
print(f"src/neighbors/ball_cover/detail/ball_cover/{path}")

path = "registers_eps_pass_euclidean.cu"
with open(path, "w") as f:
    f.write(header)
    f.write(macro_pass_eps)
    for type_path, (int_t, data_t) in types.items():
        f.write("instantiate_cuvs_neighbors_detail_rbc_eps_pass(\n")
        f.write(f"  {int_t}, {data_t}, {euclideanSq});\n")
    f.write("#undef instantiate_cuvs_neighbors_detail_rbc_eps_pass\n")
    print(f"src/neighbors/ball_cover/detail/ball_cover/{path}")
