/*
 * Copyright (c) 2025, NVIDIA CORPORATION.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

/*
 * NOTE: this file is generated by registers_00_generate.py
 *
 * Make changes there and run in this directory:
 *
 * > python registers_00_generate.py
 *
 */

#include "../../registers.cuh"
#include <cstdint>  // int64_t
#include <cuvs/neighbors/ball_cover.hpp>

#define instantiate_cuvs_neighbors_detail_rbc_eps_pass(Mvalue_idx, Mvalue_t, Mdist_func) \
  template void cuvs::neighbors::ball_cover::detail::rbc_eps_pass<Mvalue_idx, Mvalue_t>( \
    raft::resources const& handle,                                                       \
    const cuvs::neighbors::ball_cover::index<Mvalue_idx, Mvalue_t>& index,               \
    const Mvalue_t* query,                                                               \
    const int64_t n_query_rows,                                                          \
    Mvalue_t eps,                                                                        \
    const Mvalue_t* R_dists,                                                             \
    Mdist_func<Mvalue_t, int64_t>& dfunc,                                                \
    bool* adj,                                                                           \
    Mvalue_idx* vd);                                                                     \
                                                                                         \
  template void cuvs::neighbors::ball_cover::detail::rbc_eps_pass<Mvalue_idx, Mvalue_t>( \
    raft::resources const& handle,                                                       \
    const cuvs::neighbors::ball_cover::index<Mvalue_idx, Mvalue_t>& index,               \
    const Mvalue_t* query,                                                               \
    const int64_t n_query_rows,                                                          \
    Mvalue_t eps,                                                                        \
    int64_t* max_k,                                                                      \
    const Mvalue_t* R_dists,                                                             \
    Mdist_func<Mvalue_t, int64_t>& dfunc,                                                \
    Mvalue_idx* adj_ia,                                                                  \
    Mvalue_idx* adj_ja,                                                                  \
    Mvalue_idx* vd)

instantiate_cuvs_neighbors_detail_rbc_eps_pass(
  std::int64_t, float, cuvs::neighbors::ball_cover::detail::EuclideanSqFunc);
#undef instantiate_cuvs_neighbors_detail_rbc_eps_pass
